// All game content: heroes (+ specs), items, relics, mobs, bosses, events, economy.
// "mods" is the shared vocabulary read by run.js (stats) and sim.js (combat hooks). See CLAUDE.md for the full list.
(function (G) {
  const B = G.B = G.B || {};

  // ---------------------------------------------------------------- economy / pacing
  B.CFG = {
    startGold: 10, maxTeam: 3, heroCost: 7, reroll: 2,
    itemCost: { common: 3, uncommon: 4, rare: 5, epic: 8, set: 7, legendary: 10, mythic: 13 }, relicCost: 8,
    gold: { easy: 6, medium: 9, hard: 13, boss: 16 },
    xpLevels: [0, 0, 30, 85, 180, 330], // cumulative XP to reach level N (index = level); 1 XP per second alive
    maxLevel: 5, baseSlots: 1,          // item slots: 1 at Lv1-2, +1 at Lv3, Lv4, Lv5
    // by fight number (1..8). Review #22: 8 fights, bosses at 4 and 8 keep the strength they had at 3 and 6 (1.3, 2)
    fightScale: [1, 0.9, 1.0, 1.15, 1.55, 1.6, 1.8, 2.0, 2.45],
    firstFight: 0.5,  // review #22: the first fight is fought by a single hero: half the usual enemy budget
    suddenDeath: 45, fightCap: 150,     // seconds
    suddenDeathRamp: 0.01,              // review #24: sudden death burns every unit for 1%, 2%, 3%... of max HP per second
    // node sequence: F = fight (2 of easy/medium/hard), X = shop or event (2 options), B = boss (no option),
    // S = final shop choice (2 shops), G = the PvP gauntlet against player ghosts (review #9 removed the Onslaught)
    // Review #22 (David): the run starts with 1 hero and 1 relic, and each boss gets 1 more fight and 1 more shop/event
    seq: ['F', 'X', 'F', 'X', 'F', 'X', 'B', 'X', 'F', 'X', 'F', 'X', 'F', 'X', 'B', 'S', 'G'],
    startHeroes: 1, startOffer: 3,
  };

  // ---------------------------------------------------------------- heroes
  // base stats at level 1. as = attacks/sec, ms = hexes/sec, mana = max mana, m0 = starting mana
  const H = (o) => o;
  B.HEROES = {
    bastion: H({ name: 'Bastion', glyph: '🛡', role: 'Tank', color: '#4f7cff',
      hp: 950, atk: 45, armor: 45, mr: 30, as: 0.65, range: 1, ms: 2, mana: 90, m0: 30,
      abil: 'bulwark', abName: 'Bulwark', abDesc: 'Gains a shield of 30% max HP and taunts enemies within 2 hexes for 2.5s.',
      ab: { shield: 0.3, radius: 2, taunt: 2.5, allyShield: 0, burst: 0, stun: 0 },
      specs: [
        [{ id: 'bas2a', name: 'Iron Hide', desc: '+15 armor and MR, then +1 more every second in combat (up to +25).', mods: { armor: 15, mr: 15, rampArmor: 1, rampArmorCap: 25 } },
         { id: 'bas2b', name: 'Spiked Plates', desc: 'Reflects 30% of damage taken back to melee attackers.', mods: { thorns: 0.3 } }],
        [{ id: 'bas3a', name: 'Rallying Cry', desc: 'Bulwark also shields allies within 2 hexes for half the amount.', ab: { allyShield: 0.5 } },
         { id: 'bas3b', name: 'Wide Taunt', desc: 'Taunt radius +1 and lasts 1s longer.', ab: { radius: 1, taunt: 1 } }],
        [{ id: 'bas4a', name: 'Last Stand', desc: 'Once per fight, dropping below 30% HP makes Bastion invulnerable for 2s and casts Bulwark.', fl: ['laststand'] },
         { id: 'bas4b', name: 'Shield Burst', desc: 'Casting Bulwark deals magic damage equal to 60% of the shield to adjacent enemies.', ab: { burst: 0.6 } }],
        [{ id: 'bas5a', name: 'Fortress', desc: 'Shield is 60% max HP. +20% max HP.', ab: { shield: 0.3 }, mods: { hpPct: 0.2 } },
         { id: 'bas5b', name: 'Earthshaker', desc: 'Taunted enemies are also stunned for 1.2s.', ab: { stun: 1.2 } }],
      ] }),
    vex: H({ name: 'Vex', glyph: '🗡', role: 'Assassin', color: '#a05cff',
      hp: 560, atk: 72, armor: 20, mr: 20, as: 0.95, range: 1, ms: 3, mana: 60, m0: 40, crit: 0.2,
      abil: 'shadowstep', abName: 'Shadowstep', abDesc: 'Blinks next to the weakest enemy and strikes for 300% attack.',
      ab: { dmg: 3, twin: 0, execute: 0, untarg: 0, mark: 0 },
      specs: [
        [{ id: 'vex2a', name: 'Ambush', desc: 'Shadowstep always critically strikes.', fl: ['ambush'] },
         { id: 'vex2b', name: 'Venom Edge', desc: 'Attacks poison for 2% max HP per second (3s).', mods: { poisonOnHit: 0.02 } }],
        [{ id: 'vex3a', name: 'Twin Step', desc: 'Shadowstep also strikes a second nearby enemy for 60%.', ab: { twin: 0.6 } },
         { id: 'vex3b', name: 'Smoke Veil', desc: 'Untargetable for 1.5s after Shadowstep.', ab: { untarg: 1.5 } }],
        [{ id: 'vex4a', name: 'Executioner', desc: 'Shadowstep kills enemies left below 20% HP.', ab: { execute: 0.2 } },
         { id: 'vex4b', name: 'Bloodrush', desc: 'On kill: refill 60% mana and +30% attack speed for 3s.', fl: ['bloodrush'] }],
        [{ id: 'vex5a', name: 'Death Mark', desc: 'Shadowstep target takes +25% damage from all sources for 5s.', ab: { mark: 0.25 } },
         { id: 'vex5b', name: 'Phantom', desc: '+25% dodge and +1 move speed.', mods: { dodge: 0.25, ms: 1 } }],
      ] }),
    pyra: H({ name: 'Pyra', glyph: '🔥', role: 'Mage', color: '#ff7a3d',
      hp: 520, atk: 40, armor: 15, mr: 30, as: 0.75, range: 3, ms: 2, mana: 70, m0: 20,
      abil: 'fireball', abName: 'Fireball', abDesc: 'Hurls a fireball at the densest enemy group: 240% magic damage in 1 hex and burns.',
      ab: { dmg: 2.4, radius: 1, burn: 0.35, twin: 0, stun: 0, patch: 0 },
      specs: [
        [{ id: 'pyr2a', name: 'Kindling', desc: 'Burn damage doubled.', ab: { burn: 0.35 } },
         { id: 'pyr2b', name: 'Quick Cast', desc: '-20 max mana, and +3 ability power per attack.', mods: { manaMax: -20, apPerAtk: 3 } }],
        [{ id: 'pyr3a', name: 'Big Bang', desc: 'Fireball radius +1.', ab: { radius: 1 } },
         { id: 'pyr3b', name: 'Twin Flame', desc: 'A second fireball hits another group for 50%.', ab: { twin: 0.5 } }],
        [{ id: 'pyr4a', name: 'Scorched Earth', desc: 'Leaves burning ground for 3s.', ab: { patch: 3 } },
         { id: 'pyr4b', name: 'Combustion', desc: 'Burning enemies explode on death (60% attack as magic, 1 hex).', fl: ['combustion'] }],
        [{ id: 'pyr5a', name: 'Meteor', desc: '+80% fireball damage and stuns for 1s.', ab: { dmg: 1.9, stun: 1 } },
         { id: 'pyr5b', name: 'Phoenix', desc: 'Once per fight, revives at 40% HP after dying.', mods: { revive: 0.4 } }],
      ] }),
    glacia: H({ name: 'Glacia', glyph: '❄', role: 'Controller', color: '#5fd4ff',
      hp: 540, atk: 36, armor: 20, mr: 35, as: 0.7, range: 3, ms: 2, mana: 80, m0: 30,
      abil: 'blizzard', abName: 'Blizzard', abDesc: 'Freezes the densest enemy group for 1.5s (180% magic damage), then slows them.',
      ab: { dmg: 1.8, radius: 1, freeze: 1.5, slow: 0.4, shatter: 0, iceArmor: 0 },
      specs: [
        [{ id: 'gla2a', name: 'Deep Freeze', desc: 'Freeze lasts 0.7s longer.', ab: { freeze: 0.7 } },
         { id: 'gla2b', name: 'Chill Touch', desc: 'Attacks slow by 25% for 1.5s.', mods: { slowOnHit: 0.25 } }],
        [{ id: 'gla3a', name: 'Whiteout', desc: 'Blizzard radius +1.', ab: { radius: 1 } },
         { id: 'gla3b', name: 'Shatter', desc: 'Frozen enemies take +30% damage.', ab: { shatter: 0.3 } }],
        [{ id: 'gla4a', name: 'Ice Armor', desc: 'Casting shields Glacia and the weakest ally for 25% max HP.', ab: { iceArmor: 0.25 } },
         { id: 'gla4b', name: 'Frostbite', desc: 'Blizzard deals double damage.', ab: { dmg: 1.8 } }],
        [{ id: 'gla5a', name: 'Absolute Zero', desc: 'Freeze +1s and radius +1.', ab: { freeze: 1, radius: 1 } },
         { id: 'gla5b', name: 'Glacial Prison', desc: 'At fight start, freezes the toughest enemy for 3s.', fl: ['prison'] }],
      ] }),
    brakk: H({ name: 'Brakk', glyph: '🐗', role: 'Bruiser', color: '#c4513a',
      hp: 820, atk: 60, armor: 30, mr: 20, as: 0.8, range: 1, ms: 2.5, mana: 70, m0: 50, ls: 0.1,
      abil: 'charge', abName: 'Charge', abDesc: 'Charges the farthest enemy within 4 hexes, stunning adjacent enemies for 1s and gaining lifesteal.',
      ab: { dmg: 1.5, stun: 1, lsBuff: 0.3, frenzy: 0, sunder: 0, reach: 4 },
      specs: [
        [{ id: 'bra2a', name: 'Bloodthirst', desc: '+15% lifesteal.', mods: { ls: 0.15 } },
         { id: 'bra2b', name: 'Thick Hide', desc: '+150 max HP, then +1% max HP every second in combat (up to +25%).', mods: { hp: 150, rampHpPct: 0.01, rampHpPctCap: 0.25 } }],
        [{ id: 'bra3a', name: 'Stampede', desc: 'Charge stun +0.7s and reach +2.', ab: { stun: 0.7, reach: 2 } },
         { id: 'bra3b', name: 'Frenzy', desc: '+40% attack speed for 4s after charging.', ab: { frenzy: 0.4 } }],
        [{ id: 'bra4a', name: 'Rampage', desc: 'Kills refund 50% mana.', fl: ['rampage'] },
         { id: 'bra4b', name: 'Gore', desc: 'Charge deals double damage and shreds 25 armor for 5s.', ab: { dmg: 1.5, sunder: 25 } }],
        [{ id: 'bra5a', name: 'Juggernaut', desc: 'Immune to crowd control while above 50% HP.', fl: ['juggernaut'] },
         { id: 'bra5b', name: 'Warlord', desc: 'Adjacent allies gain +20% attack.', mods: { aura: [{ r: 1, stat: 'atkPct', val: 0.2 }] } }],
      ] }),
    lumen: H({ name: 'Lumen', glyph: '✚', role: 'Healer', color: '#ffe066',
      hp: 560, atk: 30, armor: 20, mr: 30, as: 0.7, range: 3, ms: 2, mana: 75, m0: 25,
      abil: 'radiance', abName: 'Radiance', abDesc: 'Heals the weakest ally for 35% of their max HP and nearby allies for 15%.',
      ab: { heal: 0.35, splash: 0.15, radius: 1, shield: 0, regen: 0, smite: 0, cleanse: 0 },
      specs: [
        [{ id: 'lum2a', name: 'Purify', desc: 'Radiance also removes stun, slow, root and silence.', ab: { cleanse: 1 } },
         { id: 'lum2b', name: 'Swift Prayer', desc: '-20 max mana.', mods: { manaMax: -20 } }],
        [{ id: 'lum3a', name: 'Sanctuary', desc: 'Splash radius +1 and splash heal +10%.', ab: { radius: 1, splash: 0.1 } },
         { id: 'lum3b', name: 'Aegis Light', desc: 'Radiance also shields the target for 15% max HP.', ab: { shield: 0.15 } }],
        [{ id: 'lum4a', name: 'Smite', desc: 'Attacks deal +50% magic damage; Radiance also smites the nearest enemy for 200%.', mods: { onHitMagic: 0.5 }, ab: { smite: 2 } },
         { id: 'lum4b', name: 'Renewal', desc: 'Radiance leaves 3% max HP regen per second for 5s.', ab: { regen: 0.03 } }],
        [{ id: 'lum5a', name: 'Resurrection', desc: 'Once per fight, revives the first fallen ally at 50% HP.', fl: ['resurrect'] },
         { id: 'lum5b', name: 'Divine Aura', desc: 'All allies gain +15 armor and magic resist.', mods: { aura: [{ r: 9, stat: 'armor', val: 15 }, { r: 9, stat: 'mr', val: 15 }] } }],
      ] }),
    kestrel: H({ name: 'Kestrel', glyph: '🏹', role: 'Ranger', color: '#7bd66b',
      hp: 520, atk: 58, armor: 15, mr: 15, as: 0.9, range: 4, ms: 2, mana: 60, m0: 0,
      abil: 'volley', abName: 'Volley', abDesc: 'Fires 5 arrows at random enemies (100% attack each). Each attack gives +3% attack speed (stacks 15x).',
      ab: { count: 5, dmg: 1, all: 0, pierce: 0, focus: 0.03, focusCap: 15 },
      specs: [
        [{ id: 'kes2a', name: 'Hawkeye', desc: '+1 range and +10% crit chance.', mods: { range: 1, crit: 0.1 } },
         { id: 'kes2b', name: 'Barbed Arrows', desc: 'Attacks poison for 1.5% max HP per second.', mods: { poisonOnHit: 0.015 } }],
        [{ id: 'kes3a', name: 'Multishot', desc: 'Attacks hit a second target for 50%.', mods: { multishot: 0.5 } },
         { id: 'kes3b', name: 'Full Quiver', desc: 'Volley fires 3 more arrows.', ab: { count: 3 } }],
        [{ id: 'kes4a', name: 'Sniper', desc: '+8% damage per hex of distance to the target.', fl: ['sniper'] },
         { id: 'kes4b', name: 'Rapid Fire', desc: 'Focus gives twice as much and stacks 30x.', ab: { focus: 0.03, focusCap: 15 } }],
        [{ id: 'kes5a', name: 'Rain of Arrows', desc: 'Volley hits every enemy.', ab: { all: 1 } },
         { id: 'kes5b', name: 'Piercing Shots', desc: 'Ignore 50% armor, +50% crit damage.', mods: { armorPen: 0.5, critDmg: 0.5 } }],
      ] }),
    morrow: H({ name: 'Morrow', glyph: '💀', role: 'Summoner', color: '#9aa3b5',
      hp: 580, atk: 36, armor: 20, mr: 30, as: 0.7, range: 3, ms: 2, mana: 70, m0: 40,
      abil: 'raise', abName: 'Raise Dead', abDesc: 'Raises 2 skeleton warriors next to Morrow.',
      ab: { count: 2, hpMul: 1, archers: 0, explode: 0, colossus: 0 },
      specs: [
        [{ id: 'mor2a', name: 'Bone Armor', desc: 'Skeletons have +50% HP.', ab: { hpMul: 0.5 } },
         { id: 'mor2b', name: 'Grave Pact', desc: 'Gains 15 mana whenever an enemy dies within 3 hexes.', fl: ['gravepact'] }],
        [{ id: 'mor3a', name: 'Legion', desc: 'Raises one more skeleton.', ab: { count: 1 } },
         { id: 'mor3b', name: 'Bone Archers', desc: 'Skeletons are archers (range 3).', ab: { archers: 1 } }],
        [{ id: 'mor4a', name: 'Corpse Explosion', desc: 'Skeletons explode on death (100% attack, 1 hex).', ab: { explode: 1 } },
         { id: 'mor4b', name: 'Soul Harvest', desc: 'Heals 5% max HP whenever any unit dies.', fl: ['soulharvest'] }],
        [{ id: 'mor5a', name: 'Bone Colossus', desc: 'Raises one giant skeleton instead (4x HP, 2x attack, taunts).', ab: { colossus: 1 } },
         { id: 'mor5b', name: 'Lich Form', desc: '+50 ability power and attacks splash 30%.', mods: { ap: 50, splash: 0.3 } }],
      ] }),
    tempest: H({ name: 'Tempest', glyph: '⚡', role: 'Mage', color: '#b9a8ff',
      hp: 510, atk: 40, armor: 15, mr: 30, as: 0.8, range: 3, ms: 2, mana: 70, m0: 30,
      abil: 'chain', abName: 'Chain Lightning', abDesc: 'Lightning bounces between 4 enemies (200% magic damage) and stuns each for 0.4s.',
      ab: { bounces: 4, dmg: 2.0, stun: 0.4, falloff: 0.1, twice: 0 },
      specs: [
        [{ id: 'tem2a', name: 'Overcharge', desc: 'Chain bounces 2 more times.', ab: { bounces: 2 } },
         { id: 'tem2b', name: 'Static', desc: 'Every 4th attack arcs to 2 more enemies for 60%.', mods: { chainEvery: 4, chainTargets: 2, chainDmg: 0.6 } }],
        [{ id: 'tem3a', name: 'Conductor', desc: 'Chain stun lasts 1s.', ab: { stun: 0.6 } },
         { id: 'tem3b', name: 'Capacitor', desc: 'Starts every fight with full mana.', mods: { manaStart: 999 } }],
        [{ id: 'tem4a', name: 'Storm Surge', desc: 'Casting gives allies within 2 hexes +30% attack speed for 4s.', fl: ['surge'] },
         { id: 'tem4b', name: 'Arc Flash', desc: 'No damage falloff and +40% chain damage.', ab: { falloff: -0.1, dmg: 0.8 } }],
        [{ id: 'tem5a', name: 'Thunderstorm', desc: 'Every 3s a bolt strikes a random enemy for 100% attack.', fl: ['thunderstorm'] },
         { id: 'tem5b', name: 'Eye of the Storm', desc: 'Chain Lightning is cast twice.', ab: { twice: 1 } }],
      ] }),
    grimhook: H({ name: 'Grimhook', glyph: '⚓', role: 'Controller', color: '#2fb3a0',
      hp: 840, atk: 56, armor: 35, mr: 30, as: 0.75, range: 1, ms: 2, mana: 70, m0: 30,
      abil: 'hook', abName: 'Hook', abDesc: 'Pulls the farthest enemy within 5 hexes next to Grimhook, dealing 120% and stunning for 1.5s.',
      ab: { reach: 5, dmg: 1.2, stun: 1.5, count: 1, vuln: 0, whirl: 0, pullAll: 0 },
      specs: [
        [{ id: 'gri2a', name: 'Barbed Chain', desc: 'Hook deals double damage and poisons.', ab: { dmg: 1.2 }, mods: { poisonOnHit: 0.01 } },
         { id: 'gri2b', name: 'Long Chain', desc: 'Hook reach +3.', ab: { reach: 3 } }],
        [{ id: 'gri3a', name: 'Double Hook', desc: 'Pulls two enemies.', ab: { count: 1 } },
         { id: 'gri3b', name: 'Anchor', desc: '+300 max HP and +15 armor.', mods: { hp: 300, armor: 15 } }],
        [{ id: 'gri4a', name: 'Drag Under', desc: 'Hooked enemies take +30% damage for 4s.', ab: { vuln: 0.3 } },
         { id: 'gri4b', name: 'Chain Whirl', desc: 'After hooking, spins to hit all adjacent enemies for 100% and slow them.', ab: { whirl: 1 } }],
        [{ id: 'gri5a', name: 'Dread Anchor', desc: 'Hook stun +1.5s.', ab: { stun: 1.5 } },
         { id: 'gri5b', name: 'Pull of the Deep', desc: 'Also drags every enemy within 3 hexes one step closer and stuns them 1s.', ab: { pullAll: 1 } }],
      ] }),
    mirage: H({ name: 'Mirage', glyph: '🎭', role: 'Trickster', color: '#ff6fb5',
      hp: 540, atk: 55, armor: 18, mr: 25, as: 0.9, range: 2, ms: 3, mana: 60, m0: 20, dodge: 0.15,
      abil: 'mirror', abName: 'Mirror Image', abDesc: 'Creates 2 decoy clones (40% stats) and blinks to the safest hex.',
      ab: { count: 2, stat: 0.4, explode: 0, backstab: 0, silence: 0 },
      specs: [
        [{ id: 'mir2a', name: 'Sharper Images', desc: 'Clones have 60% stats.', ab: { stat: 0.2 } },
         { id: 'mir2b', name: 'Evasion', desc: '+15% dodge.', mods: { dodge: 0.15 } }],
        [{ id: 'mir3a', name: 'Hall of Mirrors', desc: 'One more clone.', ab: { count: 1 } },
         { id: 'mir3b', name: 'Shatterglass', desc: 'Clones explode on death (120% attack, 1 hex) and slow.', ab: { explode: 1.2 } }],
        [{ id: 'mir4a', name: 'Backstab', desc: 'The attack after casting deals triple damage.', ab: { backstab: 3 } },
         { id: 'mir4b', name: 'Confusion', desc: 'Enemies next to a new clone are silenced for 2s.', ab: { silence: 2 } }],
        [{ id: 'mir5a', name: 'Mass Illusion', desc: 'Clones have 80% stats.', ab: { stat: 0.4 } },
         { id: 'mir5b', name: 'Phase Shift', desc: 'Once per fight, lethal damage instead leaves Mirage untargetable for 2s and heals 30%.', fl: ['phaseshift'] }],
      ] }),
    rook: H({ name: 'Rook', glyph: '⚙', role: 'Engineer', color: '#d9a441',
      hp: 620, atk: 42, armor: 25, mr: 20, as: 0.8, range: 2, ms: 2, mana: 70, m0: 50,
      abil: 'turret', abName: 'Deploy Turret', abDesc: 'Builds a turret (range 3) next to Rook. Max 2; at max, repairs them instead.',
      ab: { max: 2, hpMul: 1, asMul: 1, burn: 0, stun: 0, mortar: 0 },
      specs: [
        [{ id: 'roo2a', name: 'Reinforced', desc: 'Turrets have double HP.', ab: { hpMul: 1 } },
         { id: 'roo2b', name: 'Rapid Fire', desc: 'Turrets attack 40% faster.', ab: { asMul: 0.4 } }],
        [{ id: 'roo3a', name: 'Flamethrower', desc: 'Turret shots burn (40% attack per second).', ab: { burn: 0.4 } },
         { id: 'roo3b', name: 'Overclock', desc: 'Max turrets +1.', ab: { max: 1 } }],
        [{ id: 'roo4a', name: 'Tesla Coil', desc: 'Every 3rd turret shot stuns for 0.6s.', ab: { stun: 0.6 } },
         { id: 'roo4b', name: 'Mortar', desc: 'Turrets get range 6 and splash, but shoot slower.', ab: { mortar: 1 } }],
        [{ id: 'roo5a', name: 'Mech Suit', desc: '+50% max HP, +30% attack, attacks cleave 40%.', mods: { hpPct: 0.5, atkPct: 0.3, splash: 0.4 } },
         { id: 'roo5b', name: 'Factory', desc: 'Starts each fight with a turret already built.', fl: ['factory'] }],
      ] }),
    // ---- v5 (review #2): heroes whose power grows during the fight (passive scaling, from the start or on upgrade)
    thorne: H({ name: 'Thorne', glyph: '🪓', role: 'Berserker', color: '#d4483b',
      hp: 780, atk: 52, armor: 25, mr: 20, as: 0.8, range: 1, ms: 2.5, mana: 70, m0: 20,
      mods: { stackAtk: 2, stackAtkCap: 25 },
      abil: 'whirl', abName: 'Bloodlust', abDesc: 'Passive: +2 attack per hit (stacks 25x). Active: spins, hitting every adjacent enemy for 180% and healing 15% of the damage.',
      ab: { dmg: 1.8, heal: 0.15, radius: 1 },
      specs: [
        [{ id: 'thr2a', name: 'Scarred Hide', desc: '+150 max HP and +20 armor.', mods: { hp: 150, armor: 20 } },
         { id: 'thr2b', name: 'Unending Rage', desc: 'Bloodlust stacks 15 more times.', mods: { stackAtkCap: 15 } }],
        [{ id: 'thr3a', name: 'Wide Swing', desc: 'The spin reaches 2 hexes.', ab: { radius: 1 } },
         { id: 'thr3b', name: 'Red Thirst', desc: 'The spin heals 20% more of its damage.', ab: { heal: 0.2 } }],
        [{ id: 'thr4a', name: 'Savage', desc: '+15% crit chance and +40% crit damage.', mods: { crit: 0.15, critDmg: 0.4 } },
         { id: 'thr4b', name: 'Momentum', desc: 'Each Bloodlust stack also gives +1% attack speed.', mods: { stackAs: 0.01, stackAsCap: 40 } }],
        [{ id: 'thr5a', name: 'Undying Rage', desc: 'Once per fight, lethal damage leaves Thorne at 1 HP and invulnerable for 2s.', fl: ['undying'] },
         { id: 'thr5b', name: 'Titan Swing', desc: 'The spin deals double damage.', ab: { dmg: 1.8 } }],
      ] }),
    seraph: H({ name: 'Seraph', glyph: '😇', role: 'Paladin', color: '#f0d27a',
      hp: 860, atk: 44, armor: 35, mr: 30, as: 0.7, range: 1, ms: 2, mana: 80, m0: 30,
      mods: { rampArmor: 2, rampArmorCap: 40 },
      abil: 'consecrate', abName: 'Consecrate', abDesc: 'Passive: +2 armor and MR every second (up to +40). Active: blesses the ground around her for 4s: enemies burn, allies heal.',
      ab: { radius: 1, dur: 4, dps: 0.6, heal: 0.03, shield: 0 },
      specs: [
        [{ id: 'ser2a', name: 'Holy Plate', desc: '+20 armor.', mods: { armor: 20 } },
         { id: 'ser2b', name: 'Zealot', desc: '+15 attack.', mods: { atk: 15 } }],
        [{ id: 'ser3a', name: 'Sanctified Ground', desc: 'Consecrate radius +1.', ab: { radius: 1 } },
         { id: 'ser3b', name: 'Mending Light', desc: 'Consecrate heals twice as much.', ab: { heal: 0.03 } }],
        [{ id: 'ser4a', name: 'Divine Shield', desc: 'Casting shields Seraph for 25% max HP.', ab: { shield: 0.25 } },
         { id: 'ser4b', name: 'Judgement', desc: 'Consecrate burns twice as hard.', ab: { dps: 0.6 } }],
        [{ id: 'ser5a', name: 'Martyr', desc: 'Allies within 2 hexes gain +20 armor and MR.', mods: { aura: [{ r: 2, stat: 'armor', val: 20 }, { r: 2, stat: 'mr', val: 20 }] } },
         { id: 'ser5b', name: 'Ascension', desc: 'Her armor and MR keep growing up to +80.', mods: { rampArmorCap: 40 } }],
      ] }),
    nyx: H({ name: 'Nyx', glyph: '🌑', role: 'Hexblade', color: '#35c6d6',
      hp: 600, atk: 58, armor: 20, mr: 25, as: 0.9, range: 1, ms: 3, mana: 60, m0: 20,
      mods: { killAtk: 8, killAtkCap: 80 },
      abil: 'eclipse', abName: 'Eclipse', abDesc: 'Passive: +8 attack whenever an enemy dies within 3 hexes (up to +80). Active: her next 3 attacks deal +100% magic damage and heal her for 20% of it.',
      ab: { hits: 3, bonus: 1, heal: 0.2 },
      specs: [
        [{ id: 'nyx2a', name: 'Hunger', desc: 'Each nearby death gives +4 more attack.', mods: { killAtk: 4 } },
         { id: 'nyx2b', name: 'Shade Walk', desc: '+1 move speed and +10% dodge.', mods: { ms: 1, dodge: 0.1 } }],
        [{ id: 'nyx3a', name: 'Long Night', desc: 'Eclipse empowers 2 more attacks.', ab: { hits: 2 } },
         { id: 'nyx3b', name: 'Umbral Leech', desc: 'Eclipse heals 20% more.', ab: { heal: 0.2 } }],
        [{ id: 'nyx4a', name: 'Harvester', desc: 'Kills refund 50% mana.', fl: ['rampage'] },
         { id: 'nyx4b', name: 'Dusk Blade', desc: '+20% crit chance.', mods: { crit: 0.2 } }],
        [{ id: 'nyx5a', name: 'Endless Night', desc: 'Her kill stacks can reach +160 attack.', mods: { killAtkCap: 80 } },
         { id: 'nyx5b', name: 'Void Burst', desc: 'Eclipse attacks deal +200% instead.', ab: { bonus: 1 } }],
      ] }),
    bramble: H({ name: 'Bramble', glyph: '🌳', role: 'Warden', color: '#6a9a3a',
      hp: 1000, atk: 42, armor: 35, mr: 25, as: 0.6, range: 1, ms: 1.8, mana: 90, m0: 30,
      mods: { rampHpPct: 0.01, rampHpPctCap: 0.4 },
      abil: 'entangle', abName: 'Entangle', abDesc: 'Passive: +1% max HP every second (up to +40%). Active: roots every enemy within 2 hexes for 2s and deals 100% magic damage.',
      ab: { radius: 2, root: 2, dmg: 1, shield: 0 },
      specs: [
        [{ id: 'brm2a', name: 'Thornbark', desc: 'Reflects 25% of melee damage taken.', mods: { thorns: 0.25 } },
         { id: 'brm2b', name: 'Moss Cover', desc: 'Regenerates 1% max HP per second.', mods: { regen: 0.01 } }],
        [{ id: 'brm3a', name: 'Wide Roots', desc: 'Entangle radius +1.', ab: { radius: 1 } },
         { id: 'brm3b', name: 'Strangle', desc: 'Roots last 1s longer.', ab: { root: 1 } }],
        [{ id: 'brm4a', name: 'Barkskin', desc: 'Casting shields Bramble for 30% max HP.', ab: { shield: 0.3 } },
         { id: 'brm4b', name: 'Toxic Thorns', desc: 'Entangle deals double damage.', ab: { dmg: 1 } }],
        [{ id: 'brm5a', name: 'Ancient', desc: 'Max HP keeps growing up to +80%.', mods: { rampHpPctCap: 0.4 } },
         { id: 'brm5b', name: 'Grove Guardian', desc: 'Adjacent allies gain +15 armor.', mods: { aura: [{ r: 1, stat: 'armor', val: 15 }] } }],
      ] }),
    echo: H({ name: 'Echo', glyph: '🎻', role: 'Bard', color: '#c77dff',
      hp: 560, atk: 34, armor: 18, mr: 30, as: 0.75, range: 3, ms: 2, mana: 70, m0: 30,
      fl: ['crescendo'],
      abil: 'anthem', abName: 'Anthem', abDesc: 'Passive: every 4s all allies gain +3% attack speed (stacks 10x). Active: allies within 2 hexes heal 12% and gain +25% attack for 4s.',
      ab: { radius: 2, heal: 0.12, atk: 0.25, slow: 0, stun: 0 },
      specs: [
        [{ id: 'ech2a', name: 'Encore', desc: '-15 max mana.', mods: { manaMax: -15 } },
         { id: 'ech2b', name: 'Harmony', desc: 'Anthem heals 8% more.', ab: { heal: 0.08 } }],
        [{ id: 'ech3a', name: 'Power Chord', desc: 'Anthem gives +15% more attack.', ab: { atk: 0.15 } },
         { id: 'ech3b', name: 'Big Stage', desc: 'Anthem radius +1.', ab: { radius: 1 } }],
        [{ id: 'ech4a', name: 'Tempo', desc: 'Crescendo stacks 5 more times.', fl: ['tempo'] },
         { id: 'ech4b', name: 'Lullaby', desc: 'Anthem slows enemies within 2 hexes by 40% for 2s.', ab: { slow: 0.4 } }],
        [{ id: 'ech5a', name: 'Symphony', desc: 'Each Crescendo stack also gives +2 armor.', fl: ['symphony'] },
         { id: 'ech5b', name: 'Showstopper', desc: 'Anthem stuns adjacent enemies for 1s.', ab: { stun: 1 } }],
      ] }),
    blaze: H({ name: 'Blaze', glyph: '🔫', role: 'Gunslinger', color: '#e08a3a',
      hp: 540, atk: 50, armor: 15, mr: 15, as: 0.95, range: 3, ms: 2.5, mana: 60, m0: 10, crit: 0.1,
      mods: { critStack: 0.02, critStackCap: 0.3 },
      abil: 'fan', abName: 'Fan the Hammer', abDesc: 'Passive: every crit gives +2% crit chance (up to +30%). Active: fires 6 quick shots at the target, 70% attack each.',
      ab: { shots: 6, dmg: 0.7, ricochet: 0, splash: 0, pen: 0 },
      specs: [
        [{ id: 'blz2a', name: 'Quickdraw', desc: '+20% attack speed.', mods: { asPct: 0.2 } },
         { id: 'blz2b', name: 'Hollow Points', desc: '+10 attack.', mods: { atk: 10 } }],
        [{ id: 'blz3a', name: 'Extra Mag', desc: 'Fan the Hammer fires 3 more shots.', ab: { shots: 3 } },
         { id: 'blz3b', name: 'Ricochet', desc: 'Each shot also hits another enemy for 50%.', ab: { ricochet: 0.5 } }],
        [{ id: 'blz4a', name: 'Deadeye', desc: 'Crit stacks go up to +50%.', mods: { critStackCap: 0.2 } },
         { id: 'blz4b', name: 'Explosive Rounds', desc: 'Shots splash 30% to adjacent enemies.', ab: { splash: 0.3 } }],
        [{ id: 'blz5a', name: 'High Noon', desc: 'Shots deal 50% more and ignore 30% armor.', ab: { dmg: 0.35, pen: 0.3 } },
         { id: 'blz5b', name: 'Gunslinger', desc: '+1 range and +40% crit damage.', mods: { range: 1, critDmg: 0.4 } }],
      ] }),
    // ---- v12 (review #11, David: "many more unique heroes, go wild")
    hippolyta: H({ name: 'Hippolyta', glyph: '🔱', role: 'Amazon', color: '#c98a3a',
      hp: 620, atk: 50, armor: 22, mr: 20, as: 1.0, range: 2, ms: 2.5, mana: 60, m0: 10,
      mods: { stackAs: 0.04, stackAsCap: 10, poisonOnHit: 0.012 },
      abil: 'javelin', abName: 'Javelin Storm', abDesc: 'Passive: +4% attack speed per hit (10x) and her spear poisons. Active: hurls javelins at 3 enemies for 150% each, poisoning them for 2% max HP per second.',
      ab: { count: 3, dmg: 1.5, poison: 0.02, root: 0 },
      specs: [
        [{ id: 'hip2a', name: 'Spear Dance', desc: 'Attack speed stacks 10 more times.', mods: { stackAsCap: 10 } },
         { id: 'hip2b', name: 'Venom Tips', desc: 'Attacks poison 1% max HP per second more.', mods: { poisonOnHit: 0.01 } }],
        [{ id: 'hip3a', name: 'Volley of Spears', desc: 'Hurls 2 more javelins.', ab: { count: 2 } },
         { id: 'hip3b', name: 'Impale', desc: 'Javelins root for 1s.', ab: { root: 1 } }],
        [{ id: 'hip4a', name: 'Warrior Queen', desc: 'Allies within 2 hexes gain +15% attack speed.', mods: { aura: [{ r: 2, stat: 'asPct', val: 0.15 }] } },
         { id: 'hip4b', name: 'Fleet Foot', desc: '+1 move speed and +10% dodge.', mods: { ms: 1, dodge: 0.1 } }],
        [{ id: 'hip5a', name: 'Hydra Venom', desc: 'All her poisons deal double.', ab: { poison: 0.02 }, mods: { poisonOnHit: 0.012 } },
         { id: 'hip5b', name: 'Myrmidon', desc: '+25 attack and +1 range.', mods: { atk: 25, range: 1 } }],
      ] }),
    deadshot: H({ name: 'Deadshot', glyph: '🎯', role: 'Sniper', color: '#6a7a5a',
      hp: 480, atk: 88, armor: 12, mr: 12, as: 0.45, range: 7, ms: 1.8, mana: 70, m0: 20, crit: 0.2, fl: ['sniper'],
      abil: 'headshot', abName: 'Headshot', abDesc: 'Passive: +8% damage per hex to the target. Active: aims at the weakest enemy anywhere and fires for 400%, executing it below 15% HP.',
      ab: { dmg: 4, shots: 1, stun: 0, camo: 0, exec: 0.15 },
      specs: [
        [{ id: 'dsh2a', name: 'Steady Aim', desc: '+15% crit chance.', mods: { crit: 0.15 } },
         { id: 'dsh2b', name: 'Hollow Point', desc: 'Headshot deals 100% more.', ab: { dmg: 1 } }],
        [{ id: 'dsh3a', name: 'Double Tap', desc: 'Headshot fires twice.', ab: { shots: 1 } },
         { id: 'dsh3b', name: 'Suppressing Fire', desc: 'Headshot stuns for 1.5s.', ab: { stun: 1.5 } }],
        [{ id: 'dsh4a', name: 'Camouflage', desc: 'Untargetable for 2s after each Headshot.', ab: { camo: 2 } },
         { id: 'dsh4b', name: 'Armor Piercing', desc: 'Ignores 50% armor.', mods: { armorPen: 0.5 } }],
        [{ id: 'dsh5a', name: 'One Shot', desc: 'Headshot executes below 30% HP.', ab: { exec: 0.15 } },
         { id: 'dsh5b', name: 'Spotter', desc: '+10 mana per attack.', mods: { manaOnHit: 10 } }],
      ] }),
    vesper: H({ name: 'Vesper', glyph: '🧛', role: 'Vampire', color: '#8a1f3a',
      hp: 640, atk: 48, armor: 20, mr: 30, as: 0.85, range: 1, ms: 3, mana: 70, m0: 20, ls: 0.15,
      mods: { omni: 0.2 },
      abil: 'bloodfeast', abName: 'Blood Feast', abDesc: 'Passive: abilities heal 20% of their damage. Active: drains every enemy within 2 hexes for 120% magic damage and heals for all of it.',
      ab: { radius: 2, dmg: 1.2, share: 0, bats: 0, bleed: 0 },
      specs: [
        [{ id: 'ves2a', name: 'Thirst', desc: '+10% lifesteal.', mods: { ls: 0.1 } },
         { id: 'ves2b', name: 'Night Cloak', desc: '+15% dodge.', mods: { dodge: 0.15 } }],
        [{ id: 'ves3a', name: 'Crimson Tide', desc: 'Blood Feast radius +1.', ab: { radius: 1 } },
         { id: 'ves3b', name: 'Blood Bond', desc: 'Blood Feast also heals allies within 2 hexes for 30% of the damage.', ab: { share: 0.3 } }],
        [{ id: 'ves4a', name: 'Bat Swarm', desc: 'Blood Feast releases 2 bats.', ab: { bats: 2 } },
         { id: 'ves4b', name: 'Hemorrhage', desc: 'Drained enemies bleed for 2% max HP per second.', ab: { bleed: 0.02 } }],
        [{ id: 'ves5a', name: 'Elder Blood', desc: 'Once per fight, revives at 50% HP.', mods: { revive: 0.5 } },
         { id: 'ves5b', name: 'Sanguine Lord', desc: 'Blood Feast deals double.', ab: { dmg: 1.2 } }],
      ] }),
    kage: H({ name: 'Kage', glyph: '🥷', role: 'Ninja', color: '#3a3f55',
      hp: 560, atk: 58, armor: 18, mr: 18, as: 1.1, range: 1, ms: 3.2, mana: 55, m0: 20, dodge: 0.2,
      abil: 'smoke', abName: 'Smoke Bomb', abDesc: 'Blinds enemies within 1 hex for 1.5s (their attacks miss), vanishes for 1.5s and throws 4 shuriken for 90% each.',
      ab: { radius: 1, blind: 1.5, count: 4, dmg: 0.9, poison: 0, backstab: 0, heal: 0 },
      specs: [
        [{ id: 'kag2a', name: 'Kunai Rain', desc: 'Throws 2 more shuriken.', ab: { count: 2 } },
         { id: 'kag2b', name: 'Poisoned Stars', desc: 'Shuriken poison for 2% max HP per second.', ab: { poison: 0.02 } }],
        [{ id: 'kag3a', name: 'Thick Smoke', desc: 'Blind radius +1.', ab: { radius: 1 } },
         { id: 'kag3b', name: 'Assassinate', desc: 'The attack after the smoke deals 250%.', ab: { backstab: 2.5 } }],
        [{ id: 'kag4a', name: 'Shadow Step', desc: '+1 move speed and +10% dodge.', mods: { ms: 1, dodge: 0.1 } },
         { id: 'kag4b', name: 'Wind Walk', desc: 'The smoke heals Kage for 15% max HP.', ab: { heal: 0.15 } }],
        [{ id: 'kag5a', name: 'Twin Blades', desc: '+35% attack speed.', mods: { asPct: 0.35 } },
         { id: 'kag5b', name: 'Death Lotus', desc: 'Shuriken deal 80% more.', ab: { dmg: 0.72 } }],
      ] }),
    rex: H({ name: 'Rex', glyph: '🐕', role: 'Hound', color: '#a0703a',
      hp: 700, atk: 46, armor: 25, mr: 20, as: 1.2, range: 1, ms: 3.8, mana: 60, m0: 20, mods: { regen: 0.01 },
      abil: 'howl', abName: 'Howl & Pounce', abDesc: 'Passive: regenerates 1% HP per second. Active: allies within 3 hexes gain +20% attack and attack speed for 4s; Rex pounces on the nearest enemy and bites for 150% plus bleed.',
      ab: { radius: 3, buff: 0.2, dmg: 1.5, bleed: 0.02, stun: 0, taunt: 0, reach: 0, cleave: 0 },
      specs: [
        [{ id: 'rex2a', name: 'Good Boy', desc: '+200 max HP.', mods: { hp: 200 } },
         { id: 'rex2b', name: 'Sharp Teeth', desc: 'Attacks bleed for 1.5% max HP per second.', mods: { poisonOnHit: 0.015 } }],
        [{ id: 'rex3a', name: 'Pack Leader', desc: 'Howl reaches 2 more hexes.', ab: { radius: 2 } },
         { id: 'rex3b', name: 'Rabid', desc: 'The bite stuns for 1s.', ab: { stun: 1 } }],
        [{ id: 'rex4a', name: 'Guard Dog', desc: 'Howl taunts adjacent enemies for 2s.', ab: { taunt: 2 } },
         { id: 'rex4b', name: 'Fetch!', desc: 'Pounces on the farthest enemy within 4 hexes instead.', ab: { reach: 4 } }],
        [{ id: 'rex5a', name: 'Alpha', desc: 'Howl gives +20% more.', ab: { buff: 0.2 } },
         { id: 'rex5b', name: 'Cerberus', desc: 'The bite hits every adjacent enemy.', ab: { cleave: 1 } }],
      ] }),
    vey: H({ name: 'Vey', glyph: '🌀', role: 'Hypnotist', color: '#7a4ac8',
      hp: 520, atk: 35, armor: 15, mr: 35, as: 0.75, range: 3, ms: 2, mana: 80, m0: 30,
      abil: 'hypnosis', abName: 'Mass Hypnosis', abDesc: 'Hypnotizes the densest enemy group: for 2.5s they attack their own allies, and take 80% magic damage.',
      ab: { radius: 1, dur: 2.5, dmg: 0.8, amp: 0, shield: 0, dot: 0 },
      specs: [
        [{ id: 'vey2a', name: 'Deep Trance', desc: 'Hypnosis lasts 1s longer.', ab: { dur: 1 } },
         { id: 'vey2b', name: 'Mind Spike', desc: 'Hypnosis deals 100% more.', ab: { dmg: 0.8 } }],
        [{ id: 'vey3a', name: 'Wide Spiral', desc: 'Hypnosis radius +1.', ab: { radius: 1 } },
         { id: 'vey3b', name: 'Hypnotic Gaze', desc: 'Attacks slow by 20%.', mods: { slowOnHit: 0.2 } }],
        [{ id: 'vey4a', name: 'Puppet Master', desc: 'Hypnotized enemies deal 50% more damage (to their friends).', ab: { amp: 0.5 } },
         { id: 'vey4b', name: 'Mirror Mind', desc: 'Casting shields Vey for 25% max HP.', ab: { shield: 0.25 } }],
        [{ id: 'vey5a', name: 'Mass Delusion', desc: 'Radius +1 and 1s longer.', ab: { radius: 1, dur: 1 } },
         { id: 'vey5b', name: 'Nightmare', desc: 'Hypnotized enemies lose 5% max HP per second.', ab: { dot: 0.05 } }],
      ] }),
    pip: H({ name: 'Pip', glyph: '🤡', role: 'Clown', color: '#e0406a',
      hp: 650, atk: 46, armor: 22, mr: 22, as: 0.9, range: 2, ms: 2.5, mana: 55, m0: 25, dodge: 0.1,
      abil: 'trick', abName: 'Bag of Tricks', abDesc: 'Pulls a random trick: a pie (stuns 2s, 150%), balloons (heal allies 12%), juggling knives (5 knives, 100% each), a confetti bomb (slow 50%, 80% magic) or a squirting flower (blinds 3s).',
      ab: { pie: 2, heal: 0.12, knives: 5, silence: 0, encore: 0 },
      specs: [
        [{ id: 'pip2a', name: 'Bigger Pie', desc: 'The pie stuns 1s longer.', ab: { pie: 1 } },
         { id: 'pip2b', name: 'Encore!', desc: '25% chance to pull a second trick.', ab: { encore: 0.25 } }],
        [{ id: 'pip3a', name: 'Juggler', desc: 'Juggles 3 more knives.', ab: { knives: 3 } },
         { id: 'pip3b', name: 'Party Balloons', desc: 'Balloons heal 8% more.', ab: { heal: 0.08 } }],
        [{ id: 'pip4a', name: 'Laughing Gas', desc: 'Confetti also silences for 2s.', ab: { silence: 2 } },
         { id: 'pip4b', name: 'Rubber Nose', desc: '+200 max HP and reflects 15% of melee damage.', mods: { hp: 200, thorns: 0.15 } }],
        [{ id: 'pip5a', name: 'Grand Finale', desc: 'Always pulls two tricks.', ab: { encore: 1 } },
         { id: 'pip5b', name: 'Killer Clown', desc: '+20 attack and +20% crit chance.', mods: { atk: 20, crit: 0.2 } }],
      ] }),
    barley: H({ name: 'Barley', glyph: '🍺', role: 'Brawler', color: '#b8792a',
      hp: 820, atk: 48, armor: 28, mr: 22, as: 0.8, range: 1, ms: 2, mana: 70, m0: 30, dodge: 0.2,
      abil: 'keg', abName: 'Keg Smash', abDesc: 'Passive: drunken stagger gives 20% dodge. Active: smashes a keg on adjacent enemies for 150%, stunning 1s and slowing, then takes a swig healing 15% max HP.',
      ab: { radius: 1, dmg: 1.5, stun: 1, heal: 0.15, burn: 0 },
      specs: [
        [{ id: 'bar2a', name: 'Liquid Courage', desc: '+20% attack speed.', mods: { asPct: 0.2 } },
         { id: 'bar2b', name: 'Iron Liver', desc: 'Regenerates 1.5% max HP per second.', mods: { regen: 0.015 } }],
        [{ id: 'bar3a', name: 'Belch of Fire', desc: 'The keg burns for 40% attack per second.', ab: { burn: 0.4 } },
         { id: 'bar3b', name: 'Bar Brawl', desc: 'Keg Smash radius +1.', ab: { radius: 1 } }],
        [{ id: 'bar4a', name: 'Tipsy', desc: '+10% dodge.', mods: { dodge: 0.1 } },
         { id: 'bar4b', name: 'Hair of the Dog', desc: 'The swig heals 15% more.', ab: { heal: 0.15 } }],
        [{ id: 'bar5a', name: 'Blackout', desc: 'The stun lasts 1s longer.', ab: { stun: 1 } },
         { id: 'bar5b', name: 'Last Call', desc: 'Keg Smash deals double.', ab: { dmg: 1.5 } }],
      ] }),
    azgul: H({ name: 'Azgul', glyph: '😈', role: 'Demon', color: '#c8321e',
      hp: 720, atk: 58, armor: 25, mr: 25, as: 0.8, range: 1, ms: 2.5, mana: 70, m0: 30, mods: { rageDmg: 1 },
      abil: 'hellfire', abName: 'Hellfire', abDesc: 'Passive: +1% damage for every 1% HP missing. Active: sacrifices 10% of his current HP to blast every enemy within 2 hexes for 200% magic damage and burn them.',
      ab: { radius: 2, dmg: 2, burn: 0.4, cost: 0.1, imps: 0 },
      specs: [
        [{ id: 'azg2a', name: 'Brimstone', desc: 'Hellfire burns twice as hard.', ab: { burn: 0.4 } },
         { id: 'azg2b', name: 'Demonic Hide', desc: '+20 armor and magic resist.', mods: { armor: 20, mr: 20 } }],
        [{ id: 'azg3a', name: 'Blood Pact', desc: 'Abilities heal 25% of their damage.', mods: { omni: 0.25 } },
         { id: 'azg3b', name: 'Wider Inferno', desc: 'Hellfire radius +1.', ab: { radius: 1 } }],
        [{ id: 'azg4a', name: 'Wrath', desc: 'Missing HP gives 50% more damage.', mods: { rageDmg: 0.5 } },
         { id: 'azg4b', name: 'Imp Servants', desc: 'Hellfire summons 2 imps.', ab: { imps: 2 } }],
        [{ id: 'azg5a', name: 'Archfiend', desc: 'Hellfire costs no HP and deals double.', ab: { cost: -0.1, dmg: 2 } },
         { id: 'azg5b', name: 'Undying Flame', desc: 'Once per fight, lethal damage leaves him at 1 HP and invulnerable for 2s.', fl: ['undying'] }],
      ] }),
    grok: H({ name: 'Grok', glyph: '🪨', role: 'Caveman', color: '#8a6a4a',
      hp: 900, atk: 56, armor: 30, mr: 15, as: 0.7, range: 1, ms: 2, mana: 75, m0: 30, mods: { ccResist: 0.5 },
      abil: 'boulder', abName: 'Boulder Toss', abDesc: 'Passive: thick skull halves crowd control on him. Active: hurls a boulder at the farthest enemy within 5 hexes: 200% damage, 1.5s stun, and 100% to enemies next to it.',
      ab: { dmg: 2, stun: 1.5, radius: 1, frenzy: 0 },
      specs: [
        [{ id: 'grk2a', name: 'Big Club', desc: '+15 attack.', mods: { atk: 15 } },
         { id: 'grk2b', name: 'Tough', desc: '+250 max HP.', mods: { hp: 250 } }],
        [{ id: 'grk3a', name: 'Avalanche', desc: 'Boulder splash radius +1.', ab: { radius: 1 } },
         { id: 'grk3b', name: 'Concussion', desc: 'The stun lasts 1s longer.', ab: { stun: 1 } }],
        [{ id: 'grk4a', name: 'Unga Bunga', desc: '+40% attack speed for 4s after throwing.', ab: { frenzy: 0.4 } },
         { id: 'grk4b', name: 'Discovered Fire', desc: 'Attacks burn for 25% attack per second.', mods: { burnOnHit: 0.25 } }],
        [{ id: 'grk5a', name: 'Meteor Rock', desc: 'The boulder deals double.', ab: { dmg: 2 } },
         { id: 'grk5b', name: 'Mammoth Rider', desc: '+40% max HP and +1 move speed.', mods: { hpPct: 0.4, ms: 1 } }],
      ] }),
    imhotep: H({ name: 'Imhotep', glyph: '🧟', role: 'Mummy', color: '#c8b88a',
      hp: 760, atk: 42, armor: 30, mr: 30, as: 0.7, range: 1, ms: 1.8, mana: 80, m0: 30, mods: { revive: 0.3 },
      abil: 'wrap', abName: 'Eternal Wraps', abDesc: 'Passive: once per fight, rises again at 30% HP. Active: bandages the 2 nearest enemies: rooted 2s, healing halved, and they decay for 3% max HP per second.',
      ab: { count: 2, root: 2, decay: 0.03, shield: 0, vuln: 0 },
      specs: [
        [{ id: 'imh2a', name: 'Ancient Linen', desc: '+20 armor.', mods: { armor: 20 } },
         { id: 'imh2b', name: 'Tomb Dust', desc: 'Attacks decay for 1% max HP per second.', mods: { poisonOnHit: 0.01 } }],
        [{ id: 'imh3a', name: 'Many Wraps', desc: 'Wraps 2 more enemies.', ab: { count: 2 } },
         { id: 'imh3b', name: 'Tight Wraps', desc: 'The root lasts 1s longer.', ab: { root: 1 } }],
        [{ id: 'imh4a', name: 'Plague of Locusts', desc: 'Decay deals double.', ab: { decay: 0.03 } },
         { id: 'imh4b', name: 'Sarcophagus', desc: 'Casting shields him for 30% max HP.', ab: { shield: 0.3 } }],
        [{ id: 'imh5a', name: 'Eternal Pharaoh', desc: 'He rises at 60% HP instead.', mods: { revive: 0.3 } },
         { id: 'imh5b', name: 'Curse of the Tomb', desc: 'Wrapped enemies take 25% more damage.', ab: { vuln: 0.25 } }],
      ] }),
    leonidas: H({ name: 'Leonidas', glyph: '🏛', role: 'Hoplite', color: '#b8322a',
      hp: 880, atk: 50, armor: 40, mr: 25, as: 0.75, range: 2, ms: 2, mana: 80, m0: 30, mods: { aura: [{ r: 1, stat: 'armor', val: 10 }] },
      abil: 'phalanx', abName: 'Phalanx', abDesc: 'Passive: adjacent allies gain +10 armor. Active: raises his shield (allies within 1 hex take 30% less damage for 4s), then thrusts his spear through the 2 nearest enemies for 180%.',
      ab: { radius: 1, dr: 0.3, dmg: 1.8, hits: 2, stun: 0, taunt: 0 },
      specs: [
        [{ id: 'leo2a', name: 'Bronze Shield', desc: '+20 armor.', mods: { armor: 20 } },
         { id: 'leo2b', name: 'Long Spear', desc: '+1 range.', mods: { range: 1 } }],
        [{ id: 'leo3a', name: 'Shield Wall', desc: 'Damage reduction +15%.', ab: { dr: 0.15 } },
         { id: 'leo3b', name: 'Spartan Kick', desc: 'The thrust stuns for 1s.', ab: { stun: 1 } }],
        [{ id: 'leo4a', name: 'This Is Sparta', desc: 'Taunts enemies within 2 hexes for 2s on cast.', ab: { taunt: 2 } },
         { id: 'leo4b', name: 'Formation', desc: 'The shield covers allies within 2 hexes.', ab: { radius: 1 } }],
        [{ id: 'leo5a', name: 'Hold the Line', desc: '+40% max HP.', mods: { hpPct: 0.4 } },
         { id: 'leo5b', name: 'Hero of Thermopylae', desc: 'The thrust hits every enemy within 2 hexes.', ab: { hits: 9 } }],
      ] }),
    harlequin: H({ name: 'Harlequin', glyph: '🃏', role: 'Blade Dancer', color: '#d23a8a',
      hp: 560, atk: 56, armor: 18, mr: 20, as: 1.05, range: 1, ms: 3, mana: 60, m0: 20, crit: 0.15, mods: { critStack: 0.015, critStackCap: 0.15 },
      abil: 'waltz', abName: 'Blade Waltz', abDesc: 'Passive: each crit gives +1.5% crit (up to +15%). Active: dances through up to 3 enemies, striking each for 120%.',
      ab: { hits: 3, dmg: 1.2, silence: 0, untarg: 0 },
      specs: [
        [{ id: 'har2a', name: 'Masquerade', desc: '+15% dodge.', mods: { dodge: 0.15 } },
         { id: 'har2b', name: 'Sharp Wit', desc: '+10% crit chance.', mods: { crit: 0.1 } }],
        [{ id: 'har3a', name: 'Encore Waltz', desc: 'Strikes 2 more enemies.', ab: { hits: 2 } },
         { id: 'har3b', name: 'Mockery', desc: 'Each strike silences for 1s.', ab: { silence: 1 } }],
        [{ id: 'har4a', name: 'Grim Jester', desc: 'Kills refund 50% mana.', fl: ['rampage'] },
         { id: 'har4b', name: 'Pirouette', desc: 'Untargetable for 1s after the waltz.', ab: { untarg: 1 } }],
        [{ id: 'har5a', name: 'Final Act', desc: 'The waltz deals double.', ab: { dmg: 1.2 } },
         { id: 'har5b', name: 'Laughing Blade', desc: '+60% crit damage.', mods: { critDmg: 0.6 } }],
      ] }),
    sprocket: H({ name: 'Sprocket', glyph: '⚗', role: 'Alchemist', color: '#5ab88a',
      hp: 540, atk: 38, armor: 18, mr: 25, as: 0.8, range: 3, ms: 2, mana: 65, m0: 20,
      abil: 'flask', abName: 'Unstable Flasks', abDesc: 'Throws 3 random flasks: acid (150% magic, -20 armor), healing (15% to the weakest ally), frost (stun 1s) or poison (3% max HP per second).',
      ab: { count: 3, radius: 0, heal: 0.15, mana: 0 },
      specs: [
        [{ id: 'spr2a', name: 'Bigger Batch', desc: 'Throws 1 more flask.', ab: { count: 1 } },
         { id: 'spr2b', name: 'Reagents', desc: '+25 ability power.', mods: { ap: 25 } }],
        [{ id: 'spr3a', name: 'Volatile', desc: 'Flasks splash 1 hex.', ab: { radius: 1 } },
         { id: 'spr3b', name: 'Transmute', desc: '+3 gold after each won fight.', mods: { gold: 3 } }],
        [{ id: 'spr4a', name: 'Elixir of Life', desc: 'Healing flasks heal double.', ab: { heal: 0.15 } },
         { id: 'spr4b', name: 'Catalyst', desc: 'Each flask gives 8 mana back.', ab: { mana: 8 } }],
        [{ id: 'spr5a', name: "Philosopher's Stone", desc: '+25% to every stat.', mods: { allPct: 0.25 } },
         { id: 'spr5b', name: 'Chain Reaction', desc: 'Throws 3 more flasks.', ab: { count: 3 } }],
      ] }),
    zephyr: H({ name: 'Zephyr', glyph: '🌪', role: 'Wind Monk', color: '#7ac8c8',
      hp: 620, atk: 50, armor: 22, mr: 28, as: 1.0, range: 1, ms: 3, mana: 60, m0: 20, dodge: 0.1,
      abil: 'galekick', abName: 'Gale Kick', abDesc: 'Kicks the target 2 hexes back for 170%. Anyone it crashes into takes 100% and is stunned for 1s.',
      ab: { dmg: 1.7, push: 2, stun: 0, splash: 0, targets: 1, tailwind: 0 },
      specs: [
        [{ id: 'zep2a', name: 'Whirlwind', desc: 'The kick also hits adjacent enemies for 60%.', ab: { splash: 0.6 } },
         { id: 'zep2b', name: 'Calm Mind', desc: '-15 max mana.', mods: { manaMax: -15 } }],
        [{ id: 'zep3a', name: 'Hurricane', desc: 'Knocks back 1 hex farther.', ab: { push: 1 } },
         { id: 'zep3b', name: 'Pressure Point', desc: 'The kick stuns the target for 1.5s.', ab: { stun: 1.5 } }],
        [{ id: 'zep4a', name: 'Tailwind', desc: 'Allies within 2 hexes get +15% attack speed for 3s on cast.', ab: { tailwind: 0.15 } },
         { id: 'zep4b', name: 'Flow', desc: '+15% dodge.', mods: { dodge: 0.15 } }],
        [{ id: 'zep5a', name: 'Eye of the Storm', desc: 'The kick deals double.', ab: { dmg: 1.7 } },
         { id: 'zep5b', name: 'Seven Winds', desc: 'Kicks 2 targets.', ab: { targets: 1 } }],
      ] }),
  };
  for (const k in B.HEROES) B.HEROES[k].key = k;

  // ---------------------------------------------------------------- items (78 first, 120 since v16: see TYPES below)
  const I = (id, name, tier, mods, desc) => ({ id, name, tier, mods, desc });
  B.ITEMS = [
    // common
    I('longsword', 'Long Sword', 'common', { atk: 15 }, '+15 attack'),
    I('chainmail', 'Chainmail', 'common', { armor: 20 }, '+20 armor'),
    I('belt', "Giant's Belt", 'common', { hp: 200 }, '+200 HP'),
    I('recurve', 'Recurve Bow', 'common', { asPct: 0.2 }, '+20% attack speed'),
    I('rod', 'Rod of Power', 'common', { ap: 20 }, '+20 ability power'),
    I('cloak', 'Null Cloak', 'common', { mr: 20 }, '+20 magic resist'),
    I('tear', 'Tear Pendant', 'common', { manaStart: 20 }, '+20 starting mana'),
    I('boots', 'Swift Boots', 'common', { ms: 1 }, '+1 move speed'),
    I('gloves', 'Sparring Gloves', 'common', { crit: 0.1, dodge: 0.05 }, '+10% crit, +5% dodge'),
    I('fang', 'Vampire Fang', 'common', { ls: 0.1 }, '+10% lifesteal'),
    I('buckler', 'Buckler', 'common', { shieldStart: 150 }, 'Starts fights with a 150 shield'),
    I('cap', 'Leather Cap', 'common', { hp: 100, armor: 10 }, '+100 HP, +10 armor'),
    I('whetstone', 'Whetstone', 'common', { atk: 8, asPct: 0.08 }, '+8 attack, +8% attack speed'),
    I('coin', 'Lucky Coin', 'common', { gold: 1 }, '+1 gold after each won fight'),
    I('charm', "Scholar's Charm", 'common', { xpPct: 0.3 }, '+30% XP'),
    I('amber', 'Amber Ring', 'common', { hp: 60, armor: 6, mr: 6 }, '+60 HP, +6 armor and magic resist'),
    I('dagger', 'Dagger', 'common', { atk: 10, crit: 0.05 }, '+10 attack, +5% crit'),
    I('moss', 'Healing Moss', 'common', { regen: 0.01 }, 'Regenerate 1% max HP per second'),
    I('sling', 'Sling', 'common', { range: 1, atk: -5 }, '+1 range, -5 attack'),
    I('focus', 'Focus Crystal', 'common', { manaRegen: 2 }, '+2 mana per second'),
    // rare
    I('bloodthirster', 'Bloodthirster', 'rare', { atk: 20, ls: 0.2 }, '+20 attack, +20% lifesteal'),
    I('thornmail', 'Thornmail', 'rare', { armor: 30, thorns: 0.2 }, '+30 armor, reflects 20% melee damage'),
    I('warmog', "Warmog's Heart", 'rare', { hp: 400, regen: 0.015 }, '+400 HP, 1.5% regen per second'),
    I('crossbow', 'Rapid Crossbow', 'rare', { asPct: 0.35 }, '+35% attack speed'),
    I('deathcap', 'Deathcap', 'rare', { ap: 40 }, '+40 ability power'),
    I('visage', 'Spirit Visage', 'rare', { mr: 30, healPower: 0.25 }, '+30 magic resist, +25% healing received'),
    I('bluecrystal', 'Blue Crystal', 'rare', { manaRegen: 4 }, '+4 mana per second'),
    I('infinity', 'Infinity Edge', 'rare', { crit: 0.25, critDmg: 0.5 }, '+25% crit, +50% crit damage'),
    I('guardplate', 'Guardian Plate', 'rare', { shieldStart: 400 }, 'Starts fights with a 400 shield'),
    I('frozenhammer', 'Frozen Hammer', 'rare', { atk: 15, slowOnHit: 0.3 }, '+15 attack, attacks slow 30%'),
    I('emberblade', 'Ember Blade', 'rare', { atk: 10, burnOnHit: 0.25 }, '+10 attack, attacks burn'),
    I('venomvial', 'Venom Vial', 'rare', { poisonOnHit: 0.02 }, 'Attacks poison 2% max HP/s'),
    I('quicksilver', 'Quicksilver Sash', 'rare', { cleanseOnce: 1, mr: 15 }, 'Ignores the first crowd control, +15 MR'),
    I('phantomdancer', 'Phantom Dancer', 'rare', { dodge: 0.2, asPct: 0.15 }, '+20% dodge, +15% attack speed'),
    I('giantslayer', 'Giant Slayer', 'rare', { giantSlayer: 0.3 }, '+30% damage vs enemies with more max HP'),
    I('executioner', "Executioner's Axe", 'rare', { execute: 0.5, atk: 5 }, '+50% damage vs enemies below 30% HP'),
    I('shojin', 'Spear of Shojin', 'rare', { manaOnHit: 6, atk: 8 }, '+6 mana per attack, +8 attack'),
    I('gunblade', 'Hextech Gunblade', 'rare', { omni: 0.2, ap: 20 }, 'Abilities heal 20% of damage dealt, +20 AP'),
    I('sunfire', 'Sunfire Cape', 'rare', { hp: 200, sunfire: 0.012 }, '+200 HP, burns adjacent enemies'),
    I('scope', "Hunter's Scope", 'rare', { range: 1, crit: 0.05 }, '+1 range, +5% crit'),
    I('banner', 'War Banner', 'rare', { aura: [{ r: 1, stat: 'atkPct', val: 0.15 }] }, 'Adjacent allies +15% attack'),
    I('totem', 'Iron Totem', 'rare', { aura: [{ r: 2, stat: 'armor', val: 12 }, { r: 2, stat: 'mr', val: 12 }] }, 'Allies within 2 hexes +12 armor and MR'),
    I('needle', 'Deadly Needle', 'rare', { atk: 15, antiHeal: 1 }, '+15 attack, attacks halve enemy healing'),
    I('tabi', 'Steel Tabi', 'rare', { ms: 1, armor: 20 }, '+1 move speed, +20 armor'),
    // epic
    I('guardian', 'Guardian Angel', 'epic', { revive: 0.4, armor: 10 }, 'Revives once at 40% HP'),
    I('titan', "Titan's Resolve", 'epic', { titan: 1, hp: 100 }, 'Gains +3 attack and +3 armor per hit (max 20 stacks)'),
    I('rabadon', "Rabadon's Cap", 'epic', { ap: 80 }, '+80 ability power'),
    I('crown', "Warlord's Crown", 'epic', { allPct: 0.2 }, '+20% HP, attack, AP, armor and MR'),
    I('stormbringer', 'Stormbringer', 'epic', { chainEvery: 3, chainTargets: 3, chainDmg: 0.6, asPct: 0.1 }, 'Every 3rd attack chains to 3 enemies'),
    I('morello', 'Morellonomicon', 'epic', { ap: 25, abilityBurn: 0.03 }, 'Abilities burn 3% max HP/s, +25 AP'),
    I('redemption', 'Redemption', 'epic', { hp: 200, onDeathHeal: 0.35 }, 'On death, heals allies within 2 hexes for 35%'),
    I('zeke', "Zeke's Herald", 'epic', { aura: [{ r: 1, stat: 'asPct', val: 0.3 }] }, 'Adjacent allies +30% attack speed'),
    I('botrk', 'Blade of the Ruined King', 'epic', { curHpOnHit: 0.05, ls: 0.1 }, 'Attacks deal 5% current HP, +10% lifesteal'),
    I('stoneplate', 'Gargoyle Stoneplate', 'epic', { armor: 50, mr: 50, asPct: -0.1 }, '+50 armor and MR, -10% attack speed'),
    I('striders', 'Sky Striders', 'epic', { ms: 2, firstMoveAtk: 0.6 }, '+2 move speed, attack after moving deals +60%'),
    I('archangel', "Archangel's Staff", 'epic', { ap: 25, apPerSec: 3 }, '+25 AP, +3 AP every second in combat'),
    I('lastwhisper', 'Last Whisper', 'epic', { armorPen: 0.4, atk: 10 }, 'Ignore 40% armor, +10 attack'),
    I('dragonclaw', 'Dragon Claw', 'epic', { mr: 60, regen: 0.015 }, '+60 MR, 1.5% regen per second'),
    // ---- v5 (review #2): 20 more, several that grow during the fight
    I('knuckles', 'Spiked Knuckles', 'common', { atk: 6, stackAtk: 1, stackAtkCap: 15 }, '+6 attack, +1 attack per hit (15x)'),
    I('warpaint', 'War Paint', 'common', { rampAtk: 1, rampAtkCap: 20 }, '+1 attack every second in combat (up to +20)'),
    I('bandana', 'Bandana', 'common', { asPct: 0.15, dodge: 0.05 }, '+15% attack speed, +5% dodge'),
    I('oakshield', 'Oak Shield', 'common', { armor: 15, hp: 100 }, '+15 armor, +100 HP'),
    I('candle', 'Candle of Insight', 'common', { ap: 12, manaStart: 10 }, '+12 AP, +10 starting mana'),
    I('jerky', 'Trail Jerky', 'common', { hp: 120, regen: 0.005 }, '+120 HP, 0.5% regen per second'),
    I('whistle', 'Hunting Whistle', 'common', { ms: 1, asPct: 0.08 }, '+1 move speed, +8% attack speed'),
    I('berserkeraxe', 'Berserker Axe', 'rare', { stackAs: 0.03, stackAsCap: 15 }, '+3% attack speed per hit (15x)'),
    I('stoneheart', 'Stoneheart', 'rare', { rampArmor: 2, rampArmorCap: 30 }, '+2 armor and MR every second (up to +30)'),
    I('soulbinder', 'Soulbinder', 'rare', { killAtk: 5, killAtkCap: 40 }, '+5 attack when an enemy dies within 3 hexes (up to +40)'),
    I('frenzyblade', 'Frenzied Blade', 'rare', { atk: 10, stackAs: 0.04, stackAsCap: 12 }, '+10 attack, +4% attack speed per hit (12x)'),
    I('manaweave', 'Manaweave Robe', 'rare', { mr: 20, manaRegen: 3 }, '+20 MR, +3 mana per second'),
    I('lightningrod', 'Lightning Rod', 'rare', { asPct: 0.2, chainEvery: 4, chainTargets: 2, chainDmg: 0.5 }, '+20% attack speed, every 4th attack chains'),
    I('lifeline', 'Lifeline Amulet', 'rare', { hp: 250, shieldStartPct: 0.25 }, '+250 HP, starts fights with a 25% shield'),
    I('crackedlens', 'Cracked Lens', 'rare', { crit: 0.2, critStack: 0.02, critStackCap: 0.2 }, '+20% crit, each crit +2% crit (up to +20%)'),
    I('colossus', 'Colossus Heart', 'epic', { rampHpPct: 0.015, rampHpPctCap: 0.6 }, '+1.5% max HP every second (up to +60%)'),
    I('eclipsecrown', 'Eclipse Crown', 'epic', { ap: 40, apPerAtk: 2 }, '+40 AP, +2 AP per attack'),
    I('reaper', "Reaper's Toll", 'epic', { atk: 15, reap: 0.12 }, '+15 attack, hits execute enemies below 12% HP'),
    I('mirrorshield', 'Mirror Shield', 'epic', { mr: 30, thorns: 0.35 }, '+30 MR, reflects 35% of melee damage'),
    I('hourglass', 'Stasis Hourglass', 'epic', { ap: 20, armor: 20, stasis: 1 }, 'Once per fight at 40% HP: invulnerable for 2s'),
  ];

  // ---------------------------------------------------------------- itemization v16 (the owner: "items divided by type
  // and rarity, like Obsidian Knight"). Every item has a TYPE, which is its equipment slot: a hero wears at most one item
  // of each type (and still up to Run.slots() items in total). And a RARITY, low to high: common, uncommon, rare, epic,
  // set (pieces of a named set: 2 and 3 pieces on the same hero give set bonuses), legendary, mythic.
  B.TYPES = [
    { id: 'weapon', name: 'Weapon' }, { id: 'offhand', name: 'Off-hand' }, { id: 'helmet', name: 'Helmet' }, { id: 'armor', name: 'Armor' },
    { id: 'gloves', name: 'Gloves' }, { id: 'boots', name: 'Boots' }, { id: 'trinket', name: 'Trinket' },
  ];
  B.TYPE = {}; for (const t of B.TYPES) B.TYPE[t.id] = t;
  B.RARITIES = [
    { id: 'common', name: 'Common', color: '#b8c0cc' }, { id: 'uncommon', name: 'Uncommon', color: '#5fd47a' },
    { id: 'rare', name: 'Rare', color: '#5fa8ff' }, { id: 'epic', name: 'Epic', color: '#c77dff' },
    { id: 'set', name: 'Set', color: '#2fd6c0' }, { id: 'legendary', name: 'Legendary', color: '#ff9f40' }, { id: 'mythic', name: 'Mythic', color: '#ff4d5e' },
  ];
  B.RARITY = {}; for (const r of B.RARITIES) B.RARITY[r.id] = r;
  // the first 78 items, sorted into slots (ids never change: saved runs, ghosts and content Elo use them)
  const LEGACY_TYPE = {
    weapon: 'longsword dagger rod recurve sling crossbow bloodthirster infinity emberblade frozenhammer executioner giantslayer gunblade shojin frenzyblade berserkeraxe needle lightningrod stormbringer botrk archangel lastwhisper reaper',
    offhand: 'buckler oakshield focus guardplate bluecrystal banner totem zeke mirrorshield morello stoneplate hourglass',
    helmet: 'cap bandana warpaint deathcap visage crackedlens rabadon crown eclipsecrown',
    armor: 'chainmail belt cloak thornmail warmog sunfire manaweave stoneheart colossus',
    gloves: 'gloves knuckles titan dragonclaw',
    boots: 'boots tabi phantomdancer striders',
    trinket: 'tear fang coin charm amber moss whetstone jerky candle whistle venomvial quicksilver scope lifeline soulbinder guardian redemption',
  };
  for (const t in LEGACY_TYPE) for (const id of LEGACY_TYPE[t].split(' ')) B.ITEMS.find(i => i.id === id).type = t;
  // the old commons with two stats are now uncommon
  for (const id of 'gloves cap whetstone amber dagger oakshield candle jerky whistle bandana knuckles'.split(' ')) B.ITEMS.find(i => i.id === id).tier = 'uncommon';

  const N = (type, id, name, tier, mods, desc, set) => ({ id, name, type, tier, mods, desc, set });
  B.ITEMS.push(
    // slots that had few items
    N('gloves', 'g_leather', 'Leather Gloves', 'common', { asPct: 0.15 }, '+15% attack speed'),
    N('gloves', 'g_gauntlets', 'Iron Gauntlets', 'uncommon', { armor: 15, atk: 8 }, '+15 armor, +8 attack'),
    N('gloves', 'g_silk', 'Silk Gloves', 'uncommon', { ap: 15, manaOnHit: 3 }, '+15 AP, +3 mana per attack'),
    N('gloves', 'g_assassin', "Assassin's Grips", 'rare', { crit: 0.15, critDmg: 0.3 }, '+15% crit, +30% crit damage'),
    N('gloves', 'g_venom', 'Venom Claws', 'rare', { asPct: 0.15, poisonOnHit: 0.015 }, '+15% attack speed, attacks poison 1.5% max HP/s'),
    N('boots', 'b_padded', 'Padded Boots', 'common', { hp: 150 }, '+150 HP'),
    N('boots', 'b_treads', 'Mercury Treads', 'uncommon', { ms: 1, mr: 15 }, '+1 move speed, +15 MR'),
    N('boots', 'b_greaves', 'Berserker Greaves', 'rare', { ms: 1, asPct: 0.25 }, '+1 move speed, +25% attack speed'),
    N('boots', 'b_shadow', 'Shadow Steps', 'rare', { dodge: 0.15, firstMoveAtk: 0.3 }, '+15% dodge, attack after moving deals +30%'),
    N('helmet', 'h_iron', 'Iron Helm', 'common', { armor: 12, mr: 12 }, '+12 armor and MR'),
    N('helmet', 'h_circlet', "Sage's Circlet", 'uncommon', { ap: 15, manaStart: 15 }, '+15 AP, +15 starting mana'),
    N('armor', 'a_jerkin', 'Leather Jerkin', 'common', { hp: 120, dodge: 0.04 }, '+120 HP, +4% dodge'),
    N('armor', 'a_plate', "Knight's Plate", 'uncommon', { armor: 22, hp: 80 }, '+22 armor, +80 HP'),
    // legendary: one per slot
    N('weapon', 'obsidianblade', 'Obsidian Greatsword', 'legendary', { atk: 30, splash: 0.35, armorPen: 0.2 }, '+30 attack, attacks splash 35% to adjacent enemies, ignore 20% armor'),
    N('offhand', 'aegis', 'Aegis of Dawn', 'legendary', { shieldStartPct: 0.3, aura: [{ r: 1, stat: 'armor', val: 20 }, { r: 1, stat: 'mr', val: 20 }] }, 'Starts fights with a 30% shield, adjacent allies +20 armor and MR'),
    N('helmet', 'magicrown', 'Crown of the Magi', 'legendary', { ap: 60, manaStart: 30, manaRegen: 2 }, '+60 AP, +30 starting mana, +2 mana per second'),
    N('armor', 'dragonscale', 'Dragonscale Mail', 'legendary', { hp: 350, armor: 30, mr: 30, dmgReduce: 0.1 }, '+350 HP, +30 armor and MR, takes 10% less damage'),
    N('gloves', 'furygauntlets', 'Gauntlets of Fury', 'legendary', { asPct: 0.25, rageDmg: 0.5 }, '+25% attack speed, up to +50% damage as HP drops'),
    N('boots', 'windwalkers', 'Windwalker Boots', 'legendary', { ms: 2, dodge: 0.2, asPct: 0.15 }, '+2 move speed, +20% dodge, +15% attack speed'),
    N('trinket', 'mountainheart', 'Heart of the Mountain', 'legendary', { hpPct: 0.25, regen: 0.015, ccResist: 0.3 }, '+25% max HP, 1.5% regen per second, crowd control 30% shorter'),
    // mythic: one per slot, only in late shops
    N('weapon', 'worldsplitter', 'Worldsplitter', 'mythic', { atk: 40, crit: 0.2, critDmg: 0.5, multishot: 0.5, reap: 0.1 }, '+40 attack, +20% crit, +50% crit damage, attacks also hit a 2nd enemy for 50%, execute enemies below 10% HP'),
    N('offhand', 'eternitytome', 'Tome of Eternity', 'mythic', { ap: 50, apPerSec: 4, abilityBurn: 0.03, manaMaxPct: -0.2 }, '+50 AP, +4 AP every second, abilities burn 3% max HP/s and need 20% less mana'),
    N('helmet', 'voidmask', 'Mask of the Void', 'mythic', { allPct: 0.25, cleanseOnce: 1, omni: 0.15 }, '+25% HP, attack, AP, armor and MR, ignores the first crowd control, abilities heal 15% of damage'),
    N('armor', 'obsidianplate', 'Obsidian Bulwark', 'mythic', { hp: 500, armor: 40, mr: 40, thorns: 0.3, stasis: 1 }, '+500 HP, +40 armor and MR, reflects 30% melee damage, once per fight at 40% HP: invulnerable for 2s'),
    N('gloves', 'ruinhands', 'Hands of Ruin', 'mythic', { asPct: 0.35, curHpOnHit: 0.06, chainEvery: 3, chainTargets: 2, chainDmg: 0.6 }, '+35% attack speed, attacks deal 6% current HP, every 3rd attack chains to 2 enemies'),
    N('boots', 'phantomboots', 'Phantom Boots', 'mythic', { ms: 2, dodge: 0.3, asPct: 0.2, firstMoveAtk: 0.8 }, '+2 move speed, +30% dodge, +20% attack speed, attack after moving deals +80%'),
    N('trinket', 'phoenixheart', 'Phoenix Heart', 'mythic', { revive: 0.7, hp: 250, onDeathHeal: 0.3 }, 'Revives once at 70% HP, +250 HP, on death heals allies within 2 hexes for 30%'),
    // sets: 3 pieces each, in 3 different slots
    N('weapon', 'obs_blade', 'Obsidian Blade', 'set', { atk: 18, armorPen: 0.15 }, '+18 attack, ignore 15% armor', 'obsidian'),
    N('helmet', 'obs_helm', 'Obsidian Helm', 'set', { armor: 20, hp: 100 }, '+20 armor, +100 HP', 'obsidian'),
    N('armor', 'obs_plate', 'Obsidian Cuirass', 'set', { armor: 25, hp: 150 }, '+25 armor, +150 HP', 'obsidian'),
    N('gloves', 'storm_gloves', 'Storm Gauntlets', 'set', { asPct: 0.15, atk: 6 }, '+15% attack speed, +6 attack', 'storm'),
    N('boots', 'storm_boots', 'Storm Treads', 'set', { ms: 1, asPct: 0.1 }, '+1 move speed, +10% attack speed', 'storm'),
    N('trinket', 'storm_sigil', 'Storm Sigil', 'set', { crit: 0.1, manaRegen: 1 }, '+10% crit, +1 mana per second', 'storm'),
    N('helmet', 'arc_hood', 'Arcanist Hood', 'set', { ap: 20, mr: 10 }, '+20 AP, +10 MR', 'arcanist'),
    N('offhand', 'arc_orb', 'Arcanist Orb', 'set', { ap: 20, manaStart: 15 }, '+20 AP, +15 starting mana', 'arcanist'),
    N('armor', 'arc_robe', 'Arcanist Robe', 'set', { mr: 20, manaRegen: 2 }, '+20 MR, +2 mana per second', 'arcanist'),
    N('weapon', 'bm_cleaver', 'Bloodmoon Cleaver', 'set', { atk: 15, ls: 0.08 }, '+15 attack, +8% lifesteal', 'bloodmoon'),
    N('gloves', 'bm_grips', 'Bloodmoon Grips', 'set', { atk: 8, crit: 0.08 }, '+8 attack, +8% crit', 'bloodmoon'),
    N('trinket', 'bm_pendant', 'Bloodmoon Pendant', 'set', { hp: 150, ls: 0.05 }, '+150 HP, +5% lifesteal', 'bloodmoon'),
    N('helmet', 'rg_hood', "Ranger's Hood", 'set', { crit: 0.08, asPct: 0.08 }, '+8% crit, +8% attack speed', 'ranger'),
    N('offhand', 'rg_quiver', "Ranger's Quiver", 'set', { asPct: 0.15 }, '+15% attack speed', 'ranger'),
    N('boots', 'rg_boots', "Ranger's Boots", 'set', { ms: 1, dodge: 0.08 }, '+1 move speed, +8% dodge', 'ranger'),
  );
  // set bonuses count the pieces worn by the SAME hero (Run.heroMods)
  B.SETS = {
    obsidian: { name: 'Obsidian Guard', bonus: { 2: { mods: { armor: 25, mr: 25 }, desc: '+25 armor and MR' }, 3: { mods: { shieldStartPct: 0.2, thorns: 0.25, atkPct: 0.15 }, desc: 'Starts fights with a 20% shield, reflects 25% melee damage, +15% attack' } } },
    storm: { name: 'Stormcaller', bonus: { 2: { mods: { asPct: 0.2 }, desc: '+20% attack speed' }, 3: { mods: { chainEvery: 3, chainTargets: 3, chainDmg: 0.5 }, desc: 'Every 3rd attack chains to 3 enemies' } } },
    arcanist: { name: 'Arcanist', bonus: { 2: { mods: { ap: 30 }, desc: '+30 AP' }, 3: { mods: { manaMaxPct: -0.25, abilityBurn: 0.02 }, desc: 'Abilities need 25% less mana and burn 2% max HP/s' } } },
    bloodmoon: { name: 'Bloodmoon', bonus: { 2: { mods: { ls: 0.12 }, desc: '+12% lifesteal' }, 3: { mods: { rageDmg: 0.6, omni: 0.1 }, desc: 'Up to +60% damage as HP drops, abilities heal 10% of damage' } } },
    ranger: { name: 'Ranger', bonus: { 2: { mods: { range: 1 }, desc: '+1 range' }, 3: { mods: { multishot: 0.5 }, desc: 'Attacks also hit a 2nd enemy for 50%' } } },
  };
  for (const sid in B.SETS) { B.SETS[sid].id = sid; B.SETS[sid].pieces = B.ITEMS.filter(i => i.set === sid).map(i => i.id); }
  B.ITEM = {}; for (const it of B.ITEMS) B.ITEM[it.id] = it;

  // ---------------------------------------------------------------- relics (24) — team-wide
  const R = (id, name, desc, o) => Object.assign({ id, name, desc }, o);
  B.RELICS = [
    R('idol', 'Golden Idol', '+3 gold after each won fight.', { gold: 3 }),
    R('drum', 'War Drum', 'All heroes +12% attack speed.', { mods: { asPct: 0.12 } }),
    R('standard', 'Iron Standard', 'All heroes +15 armor.', { mods: { armor: 15 } }),
    R('lens', 'Soul Lantern', 'All heroes +25% XP.', { mods: { xpPct: 0.25 } }),
    R('feather', 'Phoenix Feather', 'The first hero to die each fight revives at 30% HP.', { fl: 'feather' }),
    R('seal', "Merchant's Seal", 'Everything in shops costs 1 less.', { fl: 'seal' }),
    R('dice', 'Loaded Dice', 'First reroll in each shop is free.', { fl: 'dice' }),
    R('font', 'Mana Font', 'Heroes start fights with +30 mana.', { mods: { manaStart: 30 } }),
    R('bloodstone', 'Bloodstone', 'All heroes +8% lifesteal.', { mods: { ls: 0.08 } }),
    R('tooth', "Giant's Tooth", 'All heroes +150 HP.', { mods: { hp: 150 } }),
    R('wits', 'Sharpened Wits', 'All heroes +20 ability power.', { mods: { ap: 20 } }),
    R('clover', 'Four-Leaf Clover', 'All heroes +10% crit chance.', { mods: { crit: 0.1 } }),
    R('backpack', 'Adventurer’s Pack', 'Every hero gets +1 item slot.', { mods: { itemSlots: 1 } }),
    R('crest', "Hero's Crest", 'Team size limit +1 (4 heroes).', { fl: 'crest' }),
    R('vengeance', 'Vengeful Spirit', 'When a hero dies, the others gain +20% attack.', { fl: 'vengeance' }),
    R('frostsigil', 'Frost Sigil', 'Enemies start every fight slowed by 40% for 4s.', { fl: 'frostsigil' }),
    R('thunder', 'Thunder Totem', 'Every 4s lightning strikes a random enemy.', { fl: 'thunder' }),
    R('spring', 'Healing Spring', 'Heroes regenerate 1% max HP per second.', { mods: { regen: 0.01 } }),
    R('firststrike', 'Opening Gambit', 'Heroes start fights with a shield of 20% max HP.', { mods: { shieldStartPct: 0.2 } }),
    R('purse', 'Coin Purse', 'Gain 10 gold now, and +1 gold per 10 held after each fight.', { fl: 'purse' }),
    R('tome', 'Elder Tome', 'All current heroes gain 45 XP now.', { fl: 'tome' }),
    R('wind', 'Swift Wind', 'All heroes +1 move speed.', { mods: { ms: 1 } }),
    R('mark', "Hunter's Mark", '+25% damage to elites and bosses.', { mods: { eliteDmg: 0.25 } }),
    // ---- v5 (review #2)
    R('ember', 'Ember Heart', "Heroes' attacks burn for 10% attack per second.", { mods: { burnOnHit: 0.1 } }),
    R('warhorn', 'War Horn', 'Heroes start fights with +30% attack speed for 5s.', { fl: 'warhorn' }),
    R('ironwill', 'Iron Will', 'Each hero ignores the first crowd control of every fight.', { mods: { cleanseOnce: 1 } }),
    R('seed', 'Seed of Growth', 'Heroes gain +1% attack every second in combat (up to +30%).', { mods: { rampAtkPct: 0.01, rampAtkPctCap: 0.3 } }),
    R('bounty', 'Bounty Board', '+1 gold per enemy killed in a won fight (up to +6).', { fl: 'bounty' }),
    R('bloodpact', 'Blood Pact', 'Heroes +20% attack, -10% max HP.', { mods: { atkPct: 0.2, hpPct: -0.1 } }),
    R('lastbreath', 'Last Breath', 'A hero that dies explodes for 300% attack in 1 hex.', { fl: 'lastbreath' }),
    R('whetset', 'Whetstone Set', 'All heroes +8 attack.', { mods: { atk: 8 } }),
    R('battery', 'Arcane Battery', 'Abilities need 15% less mana.', { mods: { manaMaxPct: -0.15 } }),
    R('treasure', 'Treasure Map', 'Item shops stock 2 more items.', { fl: 'treasure' }),
    R('rally', 'Rally Banner', 'Each hero gives +10 armor to adjacent allies.', { mods: { aura: [{ r: 1, stat: 'armor', val: 10 }] } }),
  ];
  B.RELIC = {}; for (const r of B.RELICS) B.RELIC[r.id] = r;
  // review #14 (David): content Elo only rates what acts in a fight, so these never get a rating
  B.NONCOMBAT = { item: ['coin', 'charm'], relic: ['idol', 'lens', 'seal', 'dice', 'purse', 'tome', 'treasure', 'bounty'] };

  // ---------------------------------------------------------------- mobs (stats at fight scale 1)
  const M = (o) => o;
  B.MOBS = {
    grunt: M({ name: 'Grunt', glyph: '👺', hp: 420, atk: 34, armor: 15, mr: 10, as: 0.8, range: 1, ms: 2, cost: 1 }),
    wolf: M({ name: 'Wolf', glyph: '🐺', hp: 300, atk: 26, armor: 5, mr: 5, as: 1.2, range: 1, ms: 3.5, cost: 1 }),
    archer: M({ name: 'Archer', glyph: '🎯', hp: 300, atk: 36, armor: 5, mr: 10, as: 0.8, range: 3, ms: 2, cost: 1.2 }),
    brute: M({ name: 'Brute', glyph: '🦍', hp: 900, atk: 50, armor: 30, mr: 10, as: 0.6, range: 1, ms: 1.6, mana: 60, abil: 'smash', cost: 2 }),
    skulker: M({ name: 'Skulker', glyph: '🥷', hp: 380, atk: 48, armor: 10, mr: 10, as: 1, range: 1, ms: 3, fl: ['dive'], cost: 1.6 }),
    shaman: M({ name: 'Shaman', glyph: '🧙', hp: 360, atk: 22, armor: 10, mr: 25, as: 0.7, range: 3, ms: 2, mana: 60, abil: 'mend', cost: 1.8 }),
    bomber: M({ name: 'Bomber', glyph: '💣', hp: 320, atk: 55, armor: 5, mr: 5, as: 0.8, range: 1, ms: 3, abil: 'explode', mana: 0, cost: 1.5 }),
    shieldbearer: M({ name: 'Shieldbearer', glyph: '🪖', hp: 650, atk: 30, armor: 40, mr: 20, as: 0.7, range: 1, ms: 2, mana: 70, m0: 40, abil: 'wall', cost: 1.8 }),
    hexer: M({ name: 'Hexer', glyph: '🔮', hp: 340, atk: 30, armor: 10, mr: 30, as: 0.75, range: 3, ms: 2, mana: 55, abil: 'curse', cost: 1.8 }),
    golem: M({ name: 'Golem', glyph: '🗿', hp: 1500, atk: 55, armor: 45, mr: 30, as: 0.5, range: 1, ms: 1.4, mana: 90, abil: 'slam', cost: 3 }),
    summoner: M({ name: 'Summoner', glyph: '🕯', hp: 380, atk: 25, armor: 10, mr: 20, as: 0.6, range: 3, ms: 2, mana: 70, m0: 30, abil: 'imps', cost: 2 }),
    spitter: M({ name: 'Spitter', glyph: '🐍', hp: 330, atk: 28, armor: 10, mr: 10, as: 0.8, range: 3, ms: 2, poison: 0.015, cost: 1.4 }),
    knight: M({ name: 'Dark Knight', glyph: '♞', hp: 800, atk: 45, armor: 35, mr: 35, as: 0.8, range: 1, ms: 2.2, shield: 250, cost: 2.4 }),
    imp: M({ name: 'Imp', glyph: '😈', hp: 180, atk: 18, armor: 0, mr: 0, as: 1.2, range: 1, ms: 3.5, cost: 0.5 }),
  };
  for (const k in B.MOBS) B.MOBS[k].key = k;
  B.BOSSES = {
    gorewarden: { key: 'gorewarden', name: 'Gorewarden', glyph: '👹', boss: 1, hp: 1800, atk: 45, armor: 40, mr: 30, as: 0.65, range: 1, ms: 1.8, mana: 55, abil: 'cleave',
      desc: 'Cleaves everything around it. Calls the horde at half health and enrages at 25%.', escort: ['grunt', 'grunt', 'archer'] },
    hollowking: { key: 'hollowking', name: 'The Hollow King', glyph: '👑', boss: 2, hp: 2250, atk: 48, armor: 45, mr: 45, as: 0.7, range: 2, ms: 2, mana: 60, abil: 'nova',
      desc: 'Void Nova stuns everything near it. Rends the weakest hero from afar. Splits its court at 66% and 33%.', escort: ['hexer', 'archer'] },
  };
  B.ELITES = [
    { id: 'vampiric', name: 'Vampiric', mods: { ls: 0.3 } },
    { id: 'armored', name: 'Armored', mods: { armor: 50, mr: 50 } },
    { id: 'swift', name: 'Swift', mods: { asPct: 0.5, ms: 1 } },
    { id: 'enraged', name: 'Enraged', mods: { atkPct: 0.4 } },
    { id: 'giant', name: 'Giant', mods: { hpPct: 0.8 } },
  ];
  // pools by fight number for random formations
  B.POOLS = {
    1: ['grunt', 'wolf', 'archer', 'grunt'],
    2: ['grunt', 'wolf', 'archer', 'brute', 'spitter', 'skulker'],
    5: ['grunt', 'archer', 'brute', 'skulker', 'shaman', 'bomber', 'hexer', 'spitter', 'shieldbearer'],
    6: ['archer', 'brute', 'skulker', 'shaman', 'bomber', 'hexer', 'golem', 'summoner', 'shieldbearer', 'knight'],
  };
  B.DIFF = {
    easy: { name: 'Easy', budget: 3.2, elites: 0 },
    medium: { name: 'Medium', budget: 4.6, elites: 0 },
    hard: { name: 'Hard', budget: 5.8, elites: 1 },
  };

  // ---------------------------------------------------------------- events
  // Review #17 (David: "the pink events are kinda bad ... add more strategic depth"): every event has 3 real choices with
  // a visible price or risk. A choice can have:
  //   act     what it does (run.js eventAct): xpAll:n, xpHero:n, hpAll:p, hpHero:p, buffHero (+mods), gold:n, item:any|common,
  //           typeItem:rarity, mystery, sellFull, upgradeItem, gambleItem, gamble:bet:odds:win, relic, relicBlood:p,
  //           relicItem, respec, hire:key, take:itemId, setPiece, tradeSet, none
  //   cost    gold paid up front              target  'hero' | 'item' | 'type': the player picks what it applies to
  //   next    a modifier for the NEXT fight: enemyHp / enemyAtk (+-%), manaStart, regen, atkPct (your heroes),
  //           goldPct, reward ('legendary' item if you win it), rewardGold
  //   minRarity (item targets)
  // Events marked dyn build their choices from an offer rolled when the event opens (run.js eventChoices).
  B.EVENTS = [
    { id: 'training', name: 'Training Grounds', text: 'Old veterans offer to drill your team.', choices: [
      { label: 'Drill everyone: +20 XP to all heroes', act: 'xpAll:20' },
      { label: 'Private lessons: +55 XP to one hero', act: 'xpHero:55', target: 'hero' },
      { label: 'Hire the masters: +40 XP to all heroes', act: 'xpAll:40', cost: 5 }] },
    { id: 'merchant', name: 'Wandering Merchant', text: 'A cloaked merchant opens a heavy chest of gear.', choices: [
      { label: 'Order a rare item of the type you choose', act: 'typeItem:rare', cost: 6, target: 'type' },
      { label: 'Mystery box: 50% an epic item, 50% a common one', act: 'mystery', cost: 4 },
      { label: 'Sell one of your items for its full price', act: 'sellFull', target: 'item' }] },
    { id: 'gambler', name: "Gambler's Den", text: 'Double or nothing, stranger?', choices: [
      { label: 'Small bet: 50% to win 12 gold', act: 'gamble:5:0.5:12', cost: 5 },
      { label: 'High stakes: 35% to win 40 gold', act: 'gamble:12:0.35:40', cost: 12 },
      { label: 'Bet an item: 50% it goes up one rarity, 50% it is lost', act: 'gambleItem', target: 'item' }] },
    { id: 'altar', name: 'Cursed Altar', text: 'A relic rests on a humming altar. Something watches.', choices: [
      { label: 'Take the relic. The next fight: enemies +30% HP', act: 'relic', next: { enemyHp: 0.3 } },
      { label: 'Blood price: one hero loses 10% max HP for good, you take the relic', act: 'relicBlood:0.1', target: 'hero' },
      { label: 'Pry off the gold leaf: +7 gold. The next fight: enemies +15% HP', act: 'gold:7', next: { enemyHp: 0.15 } }] },
    { id: 'fountain', name: 'Fountain of Vigor', text: 'Clear water that glows faintly.', choices: [
      { label: 'Everyone drinks: +8% max HP to all heroes', act: 'hpAll:0.08' },
      { label: 'One hero bathes: +20% max HP to that hero', act: 'hpHero:0.2', target: 'hero' },
      { label: 'Fish out the coins: +6 gold', act: 'gold:6' }] },
    { id: 'mercs', name: 'Mercenary Camp', text: 'Two sellswords look for work.', dyn: true },
    { id: 'smith', name: 'Blacksmith', text: 'The forge is still hot.', choices: [
      { label: 'Sharpen: +12 attack to one hero', act: 'buffHero', mods: { atk: 12 }, target: 'hero' },
      { label: 'Reinforce: +20 armor and +20 magic resist to one hero', act: 'buffHero', mods: { armor: 20, mr: 20 }, target: 'hero' },
      { label: 'Reforge: an item becomes a random item of the same type, one rarity higher', act: 'upgradeItem', cost: 5, target: 'item' }] },
    { id: 'library', name: 'Ancient Library', text: 'Dusty tomes about forgotten wars.', choices: [
      { label: 'Battle tactics: your heroes start the next fight with +40 mana', act: 'none', next: { manaStart: 40 } },
      { label: 'Forbidden tome: one hero swaps its latest specialization for the other one', act: 'respec', target: 'hero' },
      { label: 'Loot the shelves: a random item', act: 'item:any' }] },
    { id: 'caravan', name: 'Lost Caravan', text: 'An abandoned caravan, still loaded. Its tracks lead to a camp.', choices: [
      { label: 'Take the gold: +10 gold', act: 'gold:10' },
      { label: 'Take the crate: a random item', act: 'item:any' },
      { label: 'Follow the tracks. The next fight: enemies +20% HP and attack, it pays +75% gold', act: 'none', next: { enemyHp: 0.2, enemyAtk: 0.2, goldPct: 0.75 } }] },
    { id: 'shrine', name: 'Shrine of Sacrifice', text: 'The shrine accepts offerings in exchange for power.', choices: [
      { label: 'Offer gold: gain a relic', act: 'relic', cost: 7 },
      { label: 'Offer an item (rare or better): gain a relic', act: 'relicItem', target: 'item', minRarity: 'rare' },
      { label: 'Pray: +10 XP to all heroes', act: 'xpAll:10' }] },
    { id: 'hut', name: 'Herbalist', text: 'A quiet herbalist sorts roots and powders.', choices: [
      { label: 'Healing tonic: in the next fight your heroes regenerate 2% max HP per second', act: 'none', next: { regen: 0.02 } },
      { label: 'Calming draught: one hero ignores the first crowd control of every fight', act: 'buffHero', mods: { cleanseOnce: 1 }, cost: 4, target: 'hero' },
      { label: 'Sell her your spare herbs: +5 gold', act: 'gold:5' }] },
    { id: 'recruit', name: 'Village Militia', text: 'Villagers want to learn from your heroes.', choices: [
      { label: 'Teach them: +8 gold', act: 'gold:8' },
      { label: 'Learn from them: +15 XP to all heroes', act: 'xpAll:15' },
      { label: 'Rally them: your heroes get +15% attack in the next fight', act: 'none', next: { atkPct: 0.15 } }] },
    { id: 'scout', name: "Scout's Report", text: 'A scout has seen the camp ahead.', choices: [
      { label: 'Ambush: the next fight\'s enemies start with 20% less HP', act: 'none', next: { enemyHp: -0.2 } },
      { label: 'Sabotage: the next fight\'s enemies have 15% less attack', act: 'none', next: { enemyAtk: -0.15 } },
      { label: 'Sell the map: +7 gold', act: 'gold:7' }] },
    { id: 'arena', name: 'Arena Challenge', text: 'A champion challenges your team to a harder bout.', choices: [
      { label: 'Fight for glory. The next fight: enemies +35% HP, win it for a legendary item', act: 'none', next: { enemyHp: 0.35, reward: 'legendary' } },
      { label: 'Fight for coin. The next fight: enemies +25% HP, win it for +15 gold', act: 'none', next: { enemyHp: 0.25, rewardGold: 15 } },
      { label: 'Decline and watch: +10 XP to all heroes', act: 'xpAll:10' }] },
    { id: 'armory', name: 'Armory', text: 'Racks of gear. The quartermaster lets you take one piece.', dyn: true },
    { id: 'collector', name: 'Collector', text: 'A collector trades in matched gear.', dyn: true },
  ];
  B.EVENT = {}; for (const e of B.EVENTS) B.EVENT[e.id] = e;

  // ---------------------------------------------------------------- leagues (review #21, David)
  // Everyone starts in Bronze. 10 league points move you up one league; Celestial has no ceiling. +1 for each gauntlet
  // duel won, -2 when a run ends before the gauntlet (a PvE loss). You never drop a league (points stop at 0).
  B.LEAGUES = [
    { id: 'bronze', name: 'Bronze', color: '#b8733d', hi: '#f3bd88' },
    { id: 'silver', name: 'Silver', color: '#8e9aab', hi: '#eef3fa' },
    { id: 'gold', name: 'Gold', color: '#d19b22', hi: '#ffe38f' },
    { id: 'platinum', name: 'Platinum', color: '#2fa89a', hi: '#b5f7ec' },
    { id: 'diamond', name: 'Diamond', color: '#3f7dff', hi: '#c5dcff' },
    { id: 'celestial', name: 'Celestial', color: '#9a4dff', hi: '#f3dcff' },
  ];
  B.LEAGUE_RULES = { step: 10, duelWin: 1, pveLoss: -2 };

  // v27 (owner, 2026-09-29): Crowns, the account currency. Earned the first time you reach each league in a season
  // (leagues reset to Bronze when a season starts) and from friends you referred. Spent in the Crown Shop on perks and
  // the King Tier. Seasons are 28 days long, counted from the launch (Season 1 starts 2026-09-28).
  B.SEASON = { epoch: Date.UTC(2026, 8, 28), days: 28 };
  B.seasonOf = t => 1 + Math.max(0, Math.floor((t - B.SEASON.epoch) / (B.SEASON.days * 864e5)));
  B.seasonEnds = n => B.SEASON.epoch + n * B.SEASON.days * 864e5;
  B.CROWNS = {
    league: [0, 10, 20, 30, 50, 80],   // crowns for reaching Bronze..Celestial the first time in a season (Bronze is the start)
    referPct: 0.01, referMin: 1,       // a referrer gets 1% (at least 1) of every crown their friend earns by playing
  };
  B.SHOP = [
    { id: 'speed4', icon: '⏩', name: '4× battle speed', price: 25, desc: 'Unlocks the 4× speed button in battle. 1× and 2× stay free.' },
    { id: 'elo', icon: '📊', name: 'Content Elo', price: 20, desc: 'Unlocks the Heroes, Items and Relics tabs of the Ladder: the Elo, fights and win rate of every hero, boss, item and relic.' },
    { id: 'rename', icon: '✎', name: 'Name change', price: 10, desc: 'Pick a new name. Your ghosts take it too. Pay each time you change it.', use: true },
    { id: 'king', icon: '👑', name: 'King Tier', price: 300, king: true, desc: "The Royal board skin, only for Kings. Deeper profiles, yours and everyone else's: most played heroes, best win rate heroes, and the record of their ghosts. A crown next to your name. Includes 4× speed and Content Elo." },
  ];
  B.SHOP_ITEM = Object.fromEntries(B.SHOP.map(x => [x.id, x]));
  B.hasPerk = (perks, id) => (perks || []).includes(id) || ((id === 'speed4' || id === 'elo') && (perks || []).includes('king'));

  if (typeof module !== 'undefined') module.exports = B;
})(typeof window !== 'undefined' ? window : globalThis);
